#define USAGE_CONSUMER_CONTROL "Consumer Control"
#define USAGE_NUMERIC_KEY_PAD "Numeric Key Pad"
#define USAGE_PROGRAMMABLE_BUTTONS "Programmable Buttons"
#define USAGE_MICROPHONE "Microphone"
#define USAGE_HEADPHONE "Headphone"
#define USAGE_GRAPHIC_EQUALIZER "Graphic Equalizer"
#define USAGE__10 "+10"
#define USAGE__100 "+100"
#define USAGE_AM_PM "AM/PM"
#define USAGE_POWER "Power"
#define USAGE_RESET "Reset"
#define USAGE_SLEEP "Sleep"
#define USAGE_SLEEP_AFTER "Sleep After"
#define USAGE_SLEEP_MODE "Sleep Mode"
#define USAGE_ILLUMINATION "Illumination"
#define USAGE_FUNCTION_BUTTONS "Function Buttons"
#define USAGE_MENU "Menu"
#define USAGE_MENU_PICK "Menu Pick"
#define USAGE_MENU_UP "Menu Up"
#define USAGE_MENU_DOWN "Menu Down"
#define USAGE_MENU_LEFT "Menu Left"
#define USAGE_MENU_RIGHT "Menu Right"
#define USAGE_MENU_ESCAPE "Menu Escape"
#define USAGE_MENU_VALUE_INCREASE "Menu Value Increase"
#define USAGE_MENU_VALUE_DECREASE "Menu Value Decrease"
#define USAGE_DATA_ON_SCREEN "Data On Screen"
#define USAGE_CLOSED_CAPTION "Closed Caption"
#define USAGE_CLOSED_CAPTION_SELECT "Closed Caption Select"
#define USAGE_VCR_TV "VCR/TV"
#define USAGE_BROADCAST_MODE "Broadcast Mode"
#define USAGE_SNAPSHOT "Snapshot"
#define USAGE_STILL "Still"
#define USAGE_PICTURE_IN_PICTURE_TOGGLE "Picture-in-Picture Toggle"
#define USAGE_PICTURE_IN_PICTURE_SWAP "Picture-in-Picture Swap"
#define USAGE_RED_MENU_BUTTON "Red Menu Button"
#define USAGE_GREEN_MENU_BUTTON "Green Menu Button"
#define USAGE_BLUE_MENU_BUTTON "Blue Menu Button"
#define USAGE_YELLOW_MENU_BUTTON "Yellow Menu Button"
#define USAGE_ASPECT "Aspect"
#define USAGE_3D_MODE_SELECT "3D Mode Select"
#define USAGE_DISPLAY_BRIGHTNESS_INCREMENT "Display Brightness Increment"
#define USAGE_DISPLAY_BRIGHTNESS_DECREMENT "Display Brightness Decrement"
#define USAGE_DISPLAY_BRIGHTNESS "Display Brightness"
#define USAGE_DISPLAY_BACKLIGHT_TOGGLE "Display Backlight Toggle"
#define USAGE_DISPLAY_SET_BRIGHTNESS_TO_MINIMUM "Display Set Brightness to Minimum"
#define USAGE_DISPLAY_SET_BRIGHTNESS_TO_MAXIMUM "Display Set Brightness to Maximum"
#define USAGE_DISPLAY_SET_AUTO_BRIGHTNESS "Display Set Auto Brightness"
#define USAGE_CAMERA_ACCESS_ENABLED "Camera Access Enabled"
#define USAGE_CAMERA_ACCESS_DISABLED "Camera Access Disabled"
#define USAGE_CAMERA_ACCESS_TOGGLE "Camera Access Toggle"
#define USAGE_KEYBOARD_BRIGHTNESS_INCREMENT "Keyboard Brightness Increment"
#define USAGE_KEYBOARD_BRIGHTNESS_DECREMENT "Keyboard Brightness Decrement"
#define USAGE_KEYBOARD_BACKLIGHT_SET_LEVEL "Keyboard Backlight Set Level"
#define USAGE_KEYBOARD_BACKLIGHT_OOC "Keyboard Backlight OOC"
#define USAGE_KEYBOARD_BACKLIGHT_SET_MINIMUM "Keyboard Backlight Set Minimum"
#define USAGE_KEYBOARD_BACKLIGHT_SET_MAXIMUM "Keyboard Backlight Set Maximum"
#define USAGE_KEYBOARD_BACKLIGHT_AUTO "Keyboard Backlight Auto"
#define USAGE_SELECTION "Selection"
#define USAGE_ASSIGN_SELECTION "Assign Selection"
#define USAGE_MODE_STEP "Mode Step"
#define USAGE_RECALL_LAST "Recall Last"
#define USAGE_ENTER_CHANNEL "Enter Channel"
#define USAGE_ORDER_MOVIE "Order Movie"
#define USAGE_CHANNEL "Channel"
#define USAGE_MEDIA_SELECTION "Media Selection"
#define USAGE_MEDIA_SELECT_COMPUTER "Media Select Computer"
#define USAGE_MEDIA_SELECT_TV "Media Select TV"
#define USAGE_MEDIA_SELECT_WWW "Media Select WWW"
#define USAGE_MEDIA_SELECT_DVD "Media Select DVD"
#define USAGE_MEDIA_SELECT_TELEPHONE "Media Select Telephone"
#define USAGE_MEDIA_SELECT_PROGRAM_GUIDE "Media Select Program Guide"
#define USAGE_MEDIA_SELECT_VIDEO_PHONE "Media Select Video Phone"
#define USAGE_MEDIA_SELECT_GAMES "Media Select Games"
#define USAGE_MEDIA_SELECT_MESSAGES "Media Select Messages"
#define USAGE_MEDIA_SELECT_CD "Media Select CD"
#define USAGE_MEDIA_SELECT_VCR "Media Select VCR"
#define USAGE_MEDIA_SELECT_TUNER "Media Select Tuner"
#define USAGE_QUIT "Quit"
#define USAGE_HELP "Help"
#define USAGE_MEDIA_SELECT_TAPE "Media Select Tape"
#define USAGE_MEDIA_SELECT_CABLE "Media Select Cable"
#define USAGE_MEDIA_SELECT_SATELLITE "Media Select Satellite"
#define USAGE_MEDIA_SELECT_SECURITY "Media Select Security"
#define USAGE_MEDIA_SELECT_HOME "Media Select Home"
#define USAGE_MEDIA_SELECT_CALL "Media Select Call"
#define USAGE_CHANNEL_INCREMENT "Channel Increment"
#define USAGE_CHANNEL_DECREMENT "Channel Decrement"
#define USAGE_MEDIA_SELECT_SAP "Media Select SAP"
#define USAGE_VCR_PLUS "VCR Plus"
#define USAGE_ONCE "Once"
#define USAGE_DAILY "Daily"
#define USAGE_WEEKLY "Weekly"
#define USAGE_MONTHLY "Monthly"
#define USAGE_PLAY "Play"
#define USAGE_PAUSE "Pause"
#define USAGE_RECORD "Record"
#define USAGE_FAST_FORWARD "Fast Forward"
#define USAGE_REWIND "Rewind"
#define USAGE_SCAN_NEXT_TRACK "Scan Next Track"
#define USAGE_SCAN_PREVIOUS_TRACK "Scan Previous Track"
#define USAGE_STOP "Stop"
#define USAGE_EJECT "Eject"
#define USAGE_RANDOM_PLAY "Random Play"
#define USAGE_SELECT_DISC "Select Disc"
#define USAGE_ENTER_DISC "Enter Disc"
#define USAGE_REPEAT "Repeat"
#define USAGE_TRACKING "Tracking"
#define USAGE_TRACK_NORMAL "Track Normal"
#define USAGE_SLOW_TRACKING "Slow Tracking"
#define USAGE_FRAME_FORWARD "Frame Forward"
#define USAGE_FRAME_BACK "Frame Back"
#define USAGE_MARK "Mark"
#define USAGE_CLEAR_MARK "Clear Mark"
#define USAGE_REPEAT_FROM_MARK "Repeat From Mark"
#define USAGE_RETURN_TO_MARK "Return To Mark"
#define USAGE_SEARCH_MARK_FORWARD "Search Mark Forward"
#define USAGE_SEARCH_MARK_BACKWARDS "Search Mark Backwards"
#define USAGE_COUNTER_RESET "Counter Reset"
#define USAGE_SHOW_COUNTER "Show Counter"
#define USAGE_TRACKING_INCREMENT "Tracking Increment"
#define USAGE_TRACKING_DECREMENT "Tracking Decrement"
#define USAGE_STOP_EJECT "Stop/Eject"
#define USAGE_PLAY_PAUSE "Play/Pause"
#define USAGE_PLAY_SKIP "Play/Skip"
#define USAGE_VOICE_COMMAND "Voice Command"
#define USAGE_INVOKE_CAPTURE_INTERFACE "Invoke Capture Interface"
#define USAGE_START_OR_STOP_GAME_RECORDING "Start or Stop Game Recording"
#define USAGE_HISTORICAL_GAME_CAPTURE "Historical Game Capture"
#define USAGE_CAPTURE_GAME_SCREENSHOT "Capture Game Screenshot"
#define USAGE_SHOW_OR_HIDE_RECORDING_INDICATOR "Show or Hide Recording Indicator"
#define USAGE_START_OR_STOP_MICROPHONE_CAPTURE "Start or Stop Microphone Capture"
#define USAGE_START_OR_STOP_CAMERA_CAPTURE "Start or Stop Camera Capture"
#define USAGE_START_OR_STOP_GAME_BROADCAST "Start or Stop Game Broadcast"
#define USAGE_START_OR_STOP_VOICE_DICTATION_SESSION "Start or Stop Voice Dictation Session"
#define USAGE_INVOKE_DISMISS_EMOJI_PICKER "Invoke/Dismiss Emoji Picker"
#define USAGE_VOLUME "Volume"
#define USAGE_BALANCE "Balance"
#define USAGE_MUTE "Mute"
#define USAGE_BASS "Bass"
#define USAGE_TREBLE "Treble"
#define USAGE_BASS_BOOST "Bass Boost"
#define USAGE_SURROUND_MODE "Surround Mode"
#define USAGE_LOUDNESS "Loudness"
#define USAGE_MPX "MPX"
#define USAGE_VOLUME_INCREMENT "Volume Increment"
#define USAGE_VOLUME_DECREMENT "Volume Decrement"
#define USAGE_SPEED_SELECT "Speed Select"
#define USAGE_PLAYBACK_SPEED "Playback Speed"
#define USAGE_STANDARD_PLAY "Standard Play"
#define USAGE_LONG_PLAY "Long Play"
#define USAGE_EXTENDED_PLAY "Extended Play"
#define USAGE_SLOW "Slow"
#define USAGE_FAN_ENABLE "Fan Enable"
#define USAGE_FAN_SPEED "Fan Speed"
#define USAGE_LIGHT_ENABLE "Light Enable"
#define USAGE_LIGHT_ILLUMINATION_LEVEL "Light Illumination Level"
#define USAGE_CLIMATE_CONTROL_ENABLE "Climate Control Enable"
#define USAGE_ROOM_TEMPERATURE "Room Temperature"
#define USAGE_SECURITY_ENABLE "Security Enable"
#define USAGE_FIRE_ALARM "Fire Alarm"
#define USAGE_POLICE_ALARM "Police Alarm"
#define USAGE_PROXIMITY "Proximity"
#define USAGE_MOTION "Motion"
#define USAGE_DURESS_ALARM "Duress Alarm"
#define USAGE_HOLDUP_ALARM "Holdup Alarm"
#define USAGE_MEDICAL_ALARM "Medical Alarm"
#define USAGE_BALANCE_RIGHT "Balance Right"
#define USAGE_BALANCE_LEFT "Balance Left"
#define USAGE_BASS_INCREMENT "Bass Increment"
#define USAGE_BASS_DECREMENT "Bass Decrement"
#define USAGE_TREBLE_INCREMENT "Treble Increment"
#define USAGE_TREBLE_DECREMENT "Treble Decrement"
#define USAGE_SPEAKER_SYSTEM "Speaker System"
#define USAGE_CHANNEL_LEFT "Channel Left"
#define USAGE_CHANNEL_RIGHT "Channel Right"
#define USAGE_CHANNEL_CENTER "Channel Center"
#define USAGE_CHANNEL_FRONT "Channel Front"
#define USAGE_CHANNEL_CENTER_FRONT "Channel Center Front"
#define USAGE_CHANNEL_SIDE "Channel Side"
#define USAGE_CHANNEL_SURROUND "Channel Surround"
#define USAGE_CHANNEL_LOW_FREQUENCY_ENHANCEMENT "Channel Low Frequency Enhancement"
#define USAGE_CHANNEL_TOP "Channel Top"
#define USAGE_CHANNEL_UNKNOWN "Channel Unknown"
#define USAGE_SUB_CHANNEL "Sub-channel"
#define USAGE_SUB_CHANNEL_INCREMENT "Sub-channel Increment"
#define USAGE_SUB_CHANNEL_DECREMENT "Sub-channel Decrement"
#define USAGE_ALTERNATE_AUDIO_INCREMENT "Alternate Audio Increment"
#define USAGE_ALTERNATE_AUDIO_DECREMENT "Alternate Audio Decrement"
#define USAGE_APPLICATION_LAUNCH_BUTTONS "Application Launch Buttons"
#define USAGE_AL_LAUNCH_BUTTON_CONFIGURATION_TOOL "AL Launch Button Configuration Tool"
#define USAGE_AL_PROGRAMMABLE_BUTTON_CONFIGURATION "AL Programmable Button Configuration"
#define USAGE_AL_CONSUMER_CONTROL_CONFIGURATION "AL Consumer Control Configuration"
#define USAGE_AL_WORD_PROCESSOR "AL Word Processor"
#define USAGE_AL_TEXT_EDITOR "AL Text Editor"
#define USAGE_AL_SPREADSHEET "AL Spreadsheet"
#define USAGE_AL_GRAPHICS_EDITOR "AL Graphics Editor"
#define USAGE_AL_PRESENTATION_APP "AL Presentation App"
#define USAGE_AL_DATABASE_APP "AL Database App"
#define USAGE_AL_EMAIL_READER "AL Email Reader"
#define USAGE_AL_NEWSREADER "AL Newsreader"
#define USAGE_AL_VOICEMAIL "AL Voicemail"
#define USAGE_AL_CONTACTS_ADDRESS_BOOK "AL Contacts/Address Book"
#define USAGE_AL_CALENDAR_SCHEDULE "AL Calendar/Schedule"
#define USAGE_AL_TASK_PROJECT_MANAGER "AL Task/Project Manager"
#define USAGE_AL_LOG_JOURNAL_TIMECARD "AL Log/Journal/Timecard"
#define USAGE_AL_CHECKBOOK_FINANCE "AL Checkbook/Finance"
#define USAGE_AL_CALCULATOR "AL Calculator"
#define USAGE_AL_A_V_CAPTURE_PLAYBACK "AL A/V Capture/Playback"
#define USAGE_AL_LOCAL_MACHINE_BROWSER "AL Local Machine Browser"
#define USAGE_AL_LAN_WAN_BROWSER "AL LAN/WAN Browser"
#define USAGE_AL_INTERNET_BROWSER "AL Internet Browser"
#define USAGE_AL_REMOTE_NETWORKING_ISP_CONNECT "AL Remote Networking/ISP Connect"
#define USAGE_AL_NETWORK_CONFERENCE "AL Network Conference"
#define USAGE_AL_NETWORK_CHAT "AL Network Chat"
#define USAGE_AL_TELEPHONY_DIALER "AL Telephony/Dialer"
#define USAGE_AL_LOGON "AL Logon"
#define USAGE_AL_LOGOFF "AL Logoff"
#define USAGE_AL_LOGON_LOGOFF "AL Logon/Logoff"
#define USAGE_AL_TERMINAL_LOCK_SCREENSAVER "AL Terminal Lock/Screensaver"
#define USAGE_AL_CONTROL_PANEL "AL Control Panel"
#define USAGE_AL_COMMAND_LINE_PROCESSOR_RUN "AL Command Line Processor/Run"
#define USAGE_AL_PROCESS_TASK_MANAGER "AL Process/Task Manager"
#define USAGE_AL_SELECT_TASK_APPLICATION "AL Select Task/Application"
#define USAGE_AL_NEXT_TASK_APPLICATION "AL Next Task/Application"
#define USAGE_AL_PREVIOUS_TASK_APPLICATION "AL Previous Task/Application"
#define USAGE_AL_PREEMPTIVE_HALT_TASK_APPLICATION "AL Preemptive Halt Task/Application"
#define USAGE_AL_INTEGRATED_HELP_CENTER "AL Integrated Help Center"
#define USAGE_AL_DOCUMENTS "AL Documents"
#define USAGE_AL_THESAURUS "AL Thesaurus"
#define USAGE_AL_DICTIONARY "AL Dictionary"
#define USAGE_AL_DESKTOP "AL Desktop"
#define USAGE_AL_SPELL_CHECK "AL Spell Check"
#define USAGE_AL_GRAMMAR_CHECK "AL Grammar Check"
#define USAGE_AL_WIRELESS_STATUS "AL Wireless Status"
#define USAGE_AL_KEYBOARD_LAYOUT "AL Keyboard Layout"
#define USAGE_AL_VIRUS_PROTECTION "AL Virus Protection"
#define USAGE_AL_ENCRYPTION "AL Encryption"
#define USAGE_AL_SCREEN_SAVER "AL Screen Saver"
#define USAGE_AL_ALARMS "AL Alarms"
#define USAGE_AL_CLOCK "AL Clock"
#define USAGE_AL_FILE_BROWSER "AL File Browser"
#define USAGE_AL_POWER_STATUS "AL Power Status"
#define USAGE_AL_IMAGE_BROWSER "AL Image Browser"
#define USAGE_AL_AUDIO_BROWSER "AL Audio Browser"
#define USAGE_AL_MOVIE_BROWSER "AL Movie Browser"
#define USAGE_AL_DIGITAL_RIGHTS_MANAGER "AL Digital Rights Manager"
#define USAGE_AL_DIGITAL_WALLET "AL Digital Wallet"
#define USAGE_AL_INSTANT_MESSAGING "AL Instant Messaging"
#define USAGE_AL_OEM_FEATURES_TIPS_TUTORIAL_BROWSER "AL OEM Features/ Tips/Tutorial Browser"
#define USAGE_AL_OEM_HELP "AL OEM Help"
#define USAGE_AL_ONLINE_COMMUNITY "AL Online Community"
#define USAGE_AL_ENTERTAINMENT_CONTENT_BROWSER "AL Entertainment Content Browser"
#define USAGE_AL_ONLINE_SHOPPING_BROWSER "AL Online Shopping Browser"
#define USAGE_AL_SMARTCARD_INFORMATION_HELP "AL SmartCard Information/Help"
#define USAGE_AL_MARKET_MONITOR_FINANCE_BROWSER "AL Market Monitor/Finance Browser"
#define USAGE_AL_CUSTOMIZED_CORPORATE_NEWS_BROWSER "AL Customized Corporate News Browser"
#define USAGE_AL_ONLINE_ACTIVITY_BROWSER "AL Online Activity Browser"
#define USAGE_AL_RESEARCH_SEARCH_BROWSER "AL Research/Search Browser"
#define USAGE_AL_AUDIO_PLAYER "AL Audio Player"
#define USAGE_AL_MESSAGE_STATUS "AL Message Status"
#define USAGE_AL_CONTACT_SYNC "AL Contact Sync"
#define USAGE_AL_NAVIGATION "AL Navigation"
#define USAGE_AL_CONTEXT_AWARE_DESKTOP_ASSISTANT "AL Context‐aware Desktop Assistant"
#define USAGE_GENERIC_GUI_APPLICATION_CONTROLS "Generic GUI Application Controls"
#define USAGE_AC_NEW "AC New"
#define USAGE_AC_OPEN "AC Open"
#define USAGE_AC_CLOSE "AC Close"
#define USAGE_AC_EXIT "AC Exit"
#define USAGE_AC_MAXIMIZE "AC Maximize"
#define USAGE_AC_MINIMIZE "AC Minimize"
#define USAGE_AC_SAVE "AC Save"
#define USAGE_AC_PRINT "AC Print"
#define USAGE_AC_PROPERTIES "AC Properties"
#define USAGE_AC_UNDO "AC Undo"
#define USAGE_AC_COPY "AC Copy"
#define USAGE_AC_CUT "AC Cut"
#define USAGE_AC_PASTE "AC Paste"
#define USAGE_AC_SELECT_ALL "AC Select All"
#define USAGE_AC_FIND "AC Find"
#define USAGE_AC_FIND_AND_REPLACE "AC Find and Replace"
#define USAGE_AC_SEARCH "AC Search"
#define USAGE_AC_GO_TO "AC Go To"
#define USAGE_AC_HOME "AC Home"
#define USAGE_AC_BACK "AC Back"
#define USAGE_AC_FORWARD "AC Forward"
#define USAGE_AC_STOP "AC Stop"
#define USAGE_AC_REFRESH "AC Refresh"
#define USAGE_AC_PREVIOUS_LINK "AC Previous Link"
#define USAGE_AC_NEXT_LINK "AC Next Link"
#define USAGE_AC_BOOKMARKS "AC Bookmarks"
#define USAGE_AC_HISTORY "AC History"
#define USAGE_AC_SUBSCRIPTIONS "AC Subscriptions"
#define USAGE_AC_ZOOM_IN "AC Zoom In"
#define USAGE_AC_ZOOM_OUT "AC Zoom Out"
#define USAGE_AC_ZOOM "AC Zoom"
#define USAGE_AC_FULL_SCREEN_VIEW "AC Full Screen View"
#define USAGE_AC_NORMAL_VIEW "AC Normal View"
#define USAGE_AC_VIEW_TOGGLE "AC View Toggle"
#define USAGE_AC_SCROLL_UP "AC Scroll Up"
#define USAGE_AC_SCROLL_DOWN "AC Scroll Down"
#define USAGE_AC_SCROLL "AC Scroll"
#define USAGE_AC_PAN_LEFT "AC Pan Left"
#define USAGE_AC_PAN_RIGHT "AC Pan Right"
#define USAGE_AC_PAN "AC Pan"
#define USAGE_AC_NEW_WINDOW "AC New Window"
#define USAGE_AC_TILE_HORIZONTALLY "AC Tile Horizontally"
#define USAGE_AC_TILE_VERTICALLY "AC Tile Vertically"
#define USAGE_AC_FORMAT "AC Format"
#define USAGE_AC_EDIT "AC Edit"
#define USAGE_AC_BOLD "AC Bold"
#define USAGE_AC_ITALICS "AC Italics"
#define USAGE_AC_UNDERLINE "AC Underline"
#define USAGE_AC_STRIKETHROUGH "AC Strikethrough"
#define USAGE_AC_SUBSCRIPT "AC Subscript"
#define USAGE_AC_SUPERSCRIPT "AC Superscript"
#define USAGE_AC_ALL_CAPS "AC All Caps"
#define USAGE_AC_ROTATE "AC Rotate"
#define USAGE_AC_RESIZE "AC Resize"
#define USAGE_AC_FLIP_HORIZONTAL "AC Flip Horizontal"
#define USAGE_AC_FLIP_VERTICAL "AC Flip Vertical"
#define USAGE_AC_MIRROR_HORIZONTAL "AC Mirror Horizontal"
#define USAGE_AC_MIRROR_VERTICAL "AC Mirror Vertical"
#define USAGE_AC_FONT_SELECT "AC Font Select"
#define USAGE_AC_FONT_COLOR "AC Font Color"
#define USAGE_AC_FONT_SIZE "AC Font Size"
#define USAGE_AC_JUSTIFY_LEFT "AC Justify Left"
#define USAGE_AC_JUSTIFY_CENTER_H "AC Justify Center H"
#define USAGE_AC_JUSTIFY_RIGHT "AC Justify Right"
#define USAGE_AC_JUSTIFY_BLOCK_H "AC Justify Block H"
#define USAGE_AC_JUSTIFY_TOP "AC Justify Top"
#define USAGE_AC_JUSTIFY_CENTER_V "AC Justify Center V"
#define USAGE_AC_JUSTIFY_BOTTOM "AC Justify Bottom"
#define USAGE_AC_JUSTIFY_BLOCK_V "AC Justify Block V"
#define USAGE_AC_INDENT_DECREASE "AC Indent Decrease"
#define USAGE_AC_INDENT_INCREASE "AC Indent Increase"
#define USAGE_AC_NUMBERED_LIST "AC Numbered List"
#define USAGE_AC_RESTART_NUMBERING "AC Restart Numbering"
#define USAGE_AC_BULLETED_LIST "AC Bulleted List"
#define USAGE_AC_PROMOTE "AC Promote"
#define USAGE_AC_DEMOTE "AC Demote"
#define USAGE_AC_YES "AC Yes"
#define USAGE_AC_NO "AC No"
#define USAGE_AC_CANCEL "AC Cancel"
#define USAGE_AC_CATALOG "AC Catalog"
#define USAGE_AC_BUY_CHECKOUT "AC Buy/Checkout"
#define USAGE_AC_ADD_TO_CART "AC Add to Cart"
#define USAGE_AC_EXPAND "AC Expand"
#define USAGE_AC_EXPAND_ALL "AC Expand All"
#define USAGE_AC_COLLAPSE "AC Collapse"
#define USAGE_AC_COLLAPSE_ALL "AC Collapse All"
#define USAGE_AC_PRINT_PREVIEW "AC Print Preview"
#define USAGE_AC_PASTE_SPECIAL "AC Paste Special"
#define USAGE_AC_INSERT_MODE "AC Insert Mode"
#define USAGE_AC_DELETE "AC Delete"
#define USAGE_AC_LOCK "AC Lock"
#define USAGE_AC_UNLOCK "AC Unlock"
#define USAGE_AC_PROTECT "AC Protect"
#define USAGE_AC_UNPROTECT "AC Unprotect"
#define USAGE_AC_ATTACH_COMMENT "AC Attach Comment"
#define USAGE_AC_DELETE_COMMENT "AC Delete Comment"
#define USAGE_AC_VIEW_COMMENT "AC View Comment"
#define USAGE_AC_SELECT_WORD "AC Select Word"
#define USAGE_AC_SELECT_SENTENCE "AC Select Sentence"
#define USAGE_AC_SELECT_PARAGRAPH "AC Select Paragraph"
#define USAGE_AC_SELECT_COLUMN "AC Select Column"
#define USAGE_AC_SELECT_ROW "AC Select Row"
#define USAGE_AC_SELECT_TABLE "AC Select Table"
#define USAGE_AC_SELECT_OBJECT "AC Select Object"
#define USAGE_AC_REDO_REPEAT "AC Redo/Repeat"
#define USAGE_AC_SORT "AC Sort"
#define USAGE_AC_SORT_ASCENDING "AC Sort Ascending"
#define USAGE_AC_SORT_DESCENDING "AC Sort Descending"
#define USAGE_AC_FILTER "AC Filter"
#define USAGE_AC_SET_CLOCK "AC Set Clock"
#define USAGE_AC_VIEW_CLOCK "AC View Clock"
#define USAGE_AC_SELECT_TIME_ZONE "AC Select Time Zone"
#define USAGE_AC_EDIT_TIME_ZONES "AC Edit Time Zones"
#define USAGE_AC_SET_ALARM "AC Set Alarm"
#define USAGE_AC_CLEAR_ALARM "AC Clear Alarm"
#define USAGE_AC_SNOOZE_ALARM "AC Snooze Alarm"
#define USAGE_AC_RESET_ALARM "AC Reset Alarm"
#define USAGE_AC_SYNCHRONIZE "AC Synchronize"
#define USAGE_AC_SEND_RECEIVE "AC Send/Receive"
#define USAGE_AC_SEND_TO "AC Send To"
#define USAGE_AC_REPLY "AC Reply"
#define USAGE_AC_REPLY_ALL "AC Reply All"
#define USAGE_AC_FORWARD_MSG "AC Forward Msg"
#define USAGE_AC_SEND "AC Send"
#define USAGE_AC_ATTACH_FILE "AC Attach File"
#define USAGE_AC_UPLOAD "AC Upload"
#define USAGE_AC_DOWNLOAD_SAVE_TARGET_AS_ "AC Download (Save Target As)"
#define USAGE_AC_SET_BORDERS "AC Set Borders"
#define USAGE_AC_INSERT_ROW "AC Insert Row"
#define USAGE_AC_INSERT_COLUMN "AC Insert Column"
#define USAGE_AC_INSERT_FILE "AC Insert File"
#define USAGE_AC_INSERT_PICTURE "AC Insert Picture"
#define USAGE_AC_INSERT_OBJECT "AC Insert Object"
#define USAGE_AC_INSERT_SYMBOL "AC Insert Symbol"
#define USAGE_AC_SAVE_AND_CLOSE "AC Save and Close"
#define USAGE_AC_RENAME "AC Rename"
#define USAGE_AC_MERGE "AC Merge"
#define USAGE_AC_SPLIT "AC Split"
#define USAGE_AC_DISRIBUTE_HORIZONTALLY "AC Disribute Horizontally"
#define USAGE_AC_DISTRIBUTE_VERTICALLY "AC Distribute Vertically"
#define USAGE_AC_NEXT_KEYBOARD_LAYOUT_SELECT "AC Next Keyboard Layout Select"
#define USAGE_AC_NAVIGATION_GUIDANCE "AC Navigation Guidance"
#define USAGE_AC_DESKTOP_SHOW_ALL_WINDOWS "AC Desktop Show All Windows"
#define USAGE_AC_SOFT_KEY_LEFT "AC Soft Key Left"
#define USAGE_AC_SOFT_KEY_RIGHT "AC Soft Key Right"
#define USAGE_AC_DESKTOP_SHOW_ALL_APPLICATIONS "AC Desktop Show All Applications"
#define USAGE_AC_IDLE_KEEP_ALIVE "AC Idle Keep Alive"
#define USAGE_EXTENDED_KEYBOARD_ATTRIBUTES_COLLECTION "Extended Keyboard Attributes Collection"
#define USAGE_KEYBOARD_FORM_FACTOR "Keyboard Form Factor"
#define USAGE_KEYBOARD_KEY_TYPE "Keyboard Key Type"
#define USAGE_KEYBOARD_PHYSICAL_LAYOUT "Keyboard Physical Layout"
#define USAGE_VENDOR_SPECIFIC_KEYBOARD_PHYSICAL_LAYOUT "Vendor‐Specific Keyboard Physical Layout"
#define USAGE_KEYBOARD_IETF_LANGUAGE_TAG_INDEX "Keyboard IETF Language Tag Index"
#define USAGE_IMPLEMENTED_KEYBOARD_INPUT_ASSIST_CONTROLS "Implemented Keyboard Input Assist Controls"
#define USAGE_KEYBOARD_INPUT_ASSIST_PREVIOUS "Keyboard Input Assist Previous"
#define USAGE_KEYBOARD_INPUT_ASSIST_NEXT "Keyboard Input Assist Next"
#define USAGE_KEYBOARD_INPUT_ASSIST_PREVIOUS_GROUP "Keyboard Input Assist Previous Group"
#define USAGE_KEYBOARD_INPUT_ASSIST_NEXT_GROUP "Keyboard Input Assist Next Group"
#define USAGE_KEYBOARD_INPUT_ASSIST_ACCEPT "Keyboard Input Assist Accept"
#define USAGE_KEYBOARD_INPUT_ASSIST_CANCEL "Keyboard Input Assist Cancel"
#define USAGE_PRIVACY_SCREEN_TOGGLE "Privacy Screen Toggle"
#define USAGE_PRIVACY_SCREEN_LEVEL_DECREMENT "Privacy Screen Level Decrement"
#define USAGE_PRIVACY_SCREEN_LEVEL_INCREMENT "Privacy Screen Level Increment"
#define USAGE_PRIVACY_SCREEN_LEVEL_MINIMUM "Privacy Screen Level Minimum"
#define USAGE_PRIVACY_SCREEN_LEVEL_MAXIMUM "Privacy Screen Level Maximum"
#define USAGE_CONTACT_EDITED "Contact Edited"
#define USAGE_CONTACT_ADDED "Contact Added"
#define USAGE_CONTACT_RECORD_ACTIVE "Contact Record Active"
#define USAGE_CONTACT_INDEX "Contact Index"
#define USAGE_CONTACT_NICKNAME "Contact Nickname"
#define USAGE_CONTACT_FIRST_NAME "Contact First Name"
#define USAGE_CONTACT_LAST_NAME "Contact Last Name"
#define USAGE_CONTACT_FULL_NAME "Contact Full Name"
#define USAGE_CONTACT_PHONE_NUMBER_PERSONAL "Contact Phone Number Personal"
#define USAGE_CONTACT_PHONE_NUMBER_BUSINESS "Contact Phone Number Business"
#define USAGE_CONTACT_PHONE_NUMBER_MOBILE "Contact Phone Number Mobile"
#define USAGE_CONTACT_PHONE_NUMBER_PAGER "Contact Phone Number Pager"
#define USAGE_CONTACT_PHONE_NUMBER_FAX "Contact Phone Number Fax"
#define USAGE_CONTACT_PHONE_NUMBER_OTHER "Contact Phone Number Other"
#define USAGE_CONTACT_EMAIL_PERSONAL "Contact Email Personal"
#define USAGE_CONTACT_EMAIL_BUSINESS "Contact Email Business"
#define USAGE_CONTACT_EMAIL_OTHER "Contact Email Other"
#define USAGE_CONTACT_EMAIL_MAIN "Contact Email Main"
#define USAGE_CONTACT_SPEED_DIAL_NUMBER "Contact Speed Dial Number"
#define USAGE_CONTACT_STATUS_FLAG "Contact Status Flag"
#define USAGE_CONTACT_MISC_ "Contact Misc."


#define USAGE_PAGE_CONSUMER {"Consumer", {\
	{1, USAGE_CONSUMER_CONTROL},\
	{2, USAGE_NUMERIC_KEY_PAD},\
	{3, USAGE_PROGRAMMABLE_BUTTONS},\
	{4, USAGE_MICROPHONE},\
	{5, USAGE_HEADPHONE},\
	{6, USAGE_GRAPHIC_EQUALIZER},\
	{32, USAGE__10},\
	{33, USAGE__100},\
	{34, USAGE_AM_PM},\
	{48, USAGE_POWER},\
	{49, USAGE_RESET},\
	{50, USAGE_SLEEP},\
	{51, USAGE_SLEEP_AFTER},\
	{52, USAGE_SLEEP_MODE},\
	{53, USAGE_ILLUMINATION},\
	{54, USAGE_FUNCTION_BUTTONS},\
	{64, USAGE_MENU},\
	{65, USAGE_MENU_PICK},\
	{66, USAGE_MENU_UP},\
	{67, USAGE_MENU_DOWN},\
	{68, USAGE_MENU_LEFT},\
	{69, USAGE_MENU_RIGHT},\
	{70, USAGE_MENU_ESCAPE},\
	{71, USAGE_MENU_VALUE_INCREASE},\
	{72, USAGE_MENU_VALUE_DECREASE},\
	{96, USAGE_DATA_ON_SCREEN},\
	{97, USAGE_CLOSED_CAPTION},\
	{98, USAGE_CLOSED_CAPTION_SELECT},\
	{99, USAGE_VCR_TV},\
	{100, USAGE_BROADCAST_MODE},\
	{101, USAGE_SNAPSHOT},\
	{102, USAGE_STILL},\
	{103, USAGE_PICTURE_IN_PICTURE_TOGGLE},\
	{104, USAGE_PICTURE_IN_PICTURE_SWAP},\
	{105, USAGE_RED_MENU_BUTTON},\
	{106, USAGE_GREEN_MENU_BUTTON},\
	{107, USAGE_BLUE_MENU_BUTTON},\
	{108, USAGE_YELLOW_MENU_BUTTON},\
	{109, USAGE_ASPECT},\
	{110, USAGE_3D_MODE_SELECT},\
	{111, USAGE_DISPLAY_BRIGHTNESS_INCREMENT},\
	{112, USAGE_DISPLAY_BRIGHTNESS_DECREMENT},\
	{113, USAGE_DISPLAY_BRIGHTNESS},\
	{114, USAGE_DISPLAY_BACKLIGHT_TOGGLE},\
	{115, USAGE_DISPLAY_SET_BRIGHTNESS_TO_MINIMUM},\
	{116, USAGE_DISPLAY_SET_BRIGHTNESS_TO_MAXIMUM},\
	{117, USAGE_DISPLAY_SET_AUTO_BRIGHTNESS},\
	{118, USAGE_CAMERA_ACCESS_ENABLED},\
	{119, USAGE_CAMERA_ACCESS_DISABLED},\
	{120, USAGE_CAMERA_ACCESS_TOGGLE},\
	{121, USAGE_KEYBOARD_BRIGHTNESS_INCREMENT},\
	{122, USAGE_KEYBOARD_BRIGHTNESS_DECREMENT},\
	{123, USAGE_KEYBOARD_BACKLIGHT_SET_LEVEL},\
	{124, USAGE_KEYBOARD_BACKLIGHT_OOC},\
	{125, USAGE_KEYBOARD_BACKLIGHT_SET_MINIMUM},\
	{126, USAGE_KEYBOARD_BACKLIGHT_SET_MAXIMUM},\
	{127, USAGE_KEYBOARD_BACKLIGHT_AUTO},\
	{128, USAGE_SELECTION},\
	{129, USAGE_ASSIGN_SELECTION},\
	{130, USAGE_MODE_STEP},\
	{131, USAGE_RECALL_LAST},\
	{132, USAGE_ENTER_CHANNEL},\
	{133, USAGE_ORDER_MOVIE},\
	{134, USAGE_CHANNEL},\
	{135, USAGE_MEDIA_SELECTION},\
	{136, USAGE_MEDIA_SELECT_COMPUTER},\
	{137, USAGE_MEDIA_SELECT_TV},\
	{138, USAGE_MEDIA_SELECT_WWW},\
	{139, USAGE_MEDIA_SELECT_DVD},\
	{140, USAGE_MEDIA_SELECT_TELEPHONE},\
	{141, USAGE_MEDIA_SELECT_PROGRAM_GUIDE},\
	{142, USAGE_MEDIA_SELECT_VIDEO_PHONE},\
	{143, USAGE_MEDIA_SELECT_GAMES},\
	{144, USAGE_MEDIA_SELECT_MESSAGES},\
	{145, USAGE_MEDIA_SELECT_CD},\
	{146, USAGE_MEDIA_SELECT_VCR},\
	{147, USAGE_MEDIA_SELECT_TUNER},\
	{148, USAGE_QUIT},\
	{149, USAGE_HELP},\
	{150, USAGE_MEDIA_SELECT_TAPE},\
	{151, USAGE_MEDIA_SELECT_CABLE},\
	{152, USAGE_MEDIA_SELECT_SATELLITE},\
	{153, USAGE_MEDIA_SELECT_SECURITY},\
	{154, USAGE_MEDIA_SELECT_HOME},\
	{155, USAGE_MEDIA_SELECT_CALL},\
	{156, USAGE_CHANNEL_INCREMENT},\
	{157, USAGE_CHANNEL_DECREMENT},\
	{158, USAGE_MEDIA_SELECT_SAP},\
	{160, USAGE_VCR_PLUS},\
	{161, USAGE_ONCE},\
	{162, USAGE_DAILY},\
	{163, USAGE_WEEKLY},\
	{164, USAGE_MONTHLY},\
	{176, USAGE_PLAY},\
	{177, USAGE_PAUSE},\
	{178, USAGE_RECORD},\
	{179, USAGE_FAST_FORWARD},\
	{180, USAGE_REWIND},\
	{181, USAGE_SCAN_NEXT_TRACK},\
	{182, USAGE_SCAN_PREVIOUS_TRACK},\
	{183, USAGE_STOP},\
	{184, USAGE_EJECT},\
	{185, USAGE_RANDOM_PLAY},\
	{186, USAGE_SELECT_DISC},\
	{187, USAGE_ENTER_DISC},\
	{188, USAGE_REPEAT},\
	{189, USAGE_TRACKING},\
	{190, USAGE_TRACK_NORMAL},\
	{191, USAGE_SLOW_TRACKING},\
	{192, USAGE_FRAME_FORWARD},\
	{193, USAGE_FRAME_BACK},\
	{194, USAGE_MARK},\
	{195, USAGE_CLEAR_MARK},\
	{196, USAGE_REPEAT_FROM_MARK},\
	{197, USAGE_RETURN_TO_MARK},\
	{198, USAGE_SEARCH_MARK_FORWARD},\
	{199, USAGE_SEARCH_MARK_BACKWARDS},\
	{200, USAGE_COUNTER_RESET},\
	{201, USAGE_SHOW_COUNTER},\
	{202, USAGE_TRACKING_INCREMENT},\
	{203, USAGE_TRACKING_DECREMENT},\
	{204, USAGE_STOP_EJECT},\
	{205, USAGE_PLAY_PAUSE},\
	{206, USAGE_PLAY_SKIP},\
	{207, USAGE_VOICE_COMMAND},\
	{208, USAGE_INVOKE_CAPTURE_INTERFACE},\
	{209, USAGE_START_OR_STOP_GAME_RECORDING},\
	{210, USAGE_HISTORICAL_GAME_CAPTURE},\
	{211, USAGE_CAPTURE_GAME_SCREENSHOT},\
	{212, USAGE_SHOW_OR_HIDE_RECORDING_INDICATOR},\
	{213, USAGE_START_OR_STOP_MICROPHONE_CAPTURE},\
	{214, USAGE_START_OR_STOP_CAMERA_CAPTURE},\
	{215, USAGE_START_OR_STOP_GAME_BROADCAST},\
	{216, USAGE_START_OR_STOP_VOICE_DICTATION_SESSION},\
	{217, USAGE_INVOKE_DISMISS_EMOJI_PICKER},\
	{224, USAGE_VOLUME},\
	{225, USAGE_BALANCE},\
	{226, USAGE_MUTE},\
	{227, USAGE_BASS},\
	{228, USAGE_TREBLE},\
	{229, USAGE_BASS_BOOST},\
	{230, USAGE_SURROUND_MODE},\
	{231, USAGE_LOUDNESS},\
	{232, USAGE_MPX},\
	{233, USAGE_VOLUME_INCREMENT},\
	{234, USAGE_VOLUME_DECREMENT},\
	{240, USAGE_SPEED_SELECT},\
	{241, USAGE_PLAYBACK_SPEED},\
	{242, USAGE_STANDARD_PLAY},\
	{243, USAGE_LONG_PLAY},\
	{244, USAGE_EXTENDED_PLAY},\
	{245, USAGE_SLOW},\
	{256, USAGE_FAN_ENABLE},\
	{257, USAGE_FAN_SPEED},\
	{258, USAGE_LIGHT_ENABLE},\
	{259, USAGE_LIGHT_ILLUMINATION_LEVEL},\
	{260, USAGE_CLIMATE_CONTROL_ENABLE},\
	{261, USAGE_ROOM_TEMPERATURE},\
	{262, USAGE_SECURITY_ENABLE},\
	{263, USAGE_FIRE_ALARM},\
	{264, USAGE_POLICE_ALARM},\
	{265, USAGE_PROXIMITY},\
	{266, USAGE_MOTION},\
	{267, USAGE_DURESS_ALARM},\
	{268, USAGE_HOLDUP_ALARM},\
	{269, USAGE_MEDICAL_ALARM},\
	{336, USAGE_BALANCE_RIGHT},\
	{337, USAGE_BALANCE_LEFT},\
	{338, USAGE_BASS_INCREMENT},\
	{339, USAGE_BASS_DECREMENT},\
	{340, USAGE_TREBLE_INCREMENT},\
	{341, USAGE_TREBLE_DECREMENT},\
	{352, USAGE_SPEAKER_SYSTEM},\
	{353, USAGE_CHANNEL_LEFT},\
	{354, USAGE_CHANNEL_RIGHT},\
	{355, USAGE_CHANNEL_CENTER},\
	{356, USAGE_CHANNEL_FRONT},\
	{357, USAGE_CHANNEL_CENTER_FRONT},\
	{358, USAGE_CHANNEL_SIDE},\
	{359, USAGE_CHANNEL_SURROUND},\
	{360, USAGE_CHANNEL_LOW_FREQUENCY_ENHANCEMENT},\
	{361, USAGE_CHANNEL_TOP},\
	{362, USAGE_CHANNEL_UNKNOWN},\
	{368, USAGE_SUB_CHANNEL},\
	{369, USAGE_SUB_CHANNEL_INCREMENT},\
	{370, USAGE_SUB_CHANNEL_DECREMENT},\
	{371, USAGE_ALTERNATE_AUDIO_INCREMENT},\
	{372, USAGE_ALTERNATE_AUDIO_DECREMENT},\
	{384, USAGE_APPLICATION_LAUNCH_BUTTONS},\
	{385, USAGE_AL_LAUNCH_BUTTON_CONFIGURATION_TOOL},\
	{386, USAGE_AL_PROGRAMMABLE_BUTTON_CONFIGURATION},\
	{387, USAGE_AL_CONSUMER_CONTROL_CONFIGURATION},\
	{388, USAGE_AL_WORD_PROCESSOR},\
	{389, USAGE_AL_TEXT_EDITOR},\
	{390, USAGE_AL_SPREADSHEET},\
	{391, USAGE_AL_GRAPHICS_EDITOR},\
	{392, USAGE_AL_PRESENTATION_APP},\
	{393, USAGE_AL_DATABASE_APP},\
	{394, USAGE_AL_EMAIL_READER},\
	{395, USAGE_AL_NEWSREADER},\
	{396, USAGE_AL_VOICEMAIL},\
	{397, USAGE_AL_CONTACTS_ADDRESS_BOOK},\
	{398, USAGE_AL_CALENDAR_SCHEDULE},\
	{399, USAGE_AL_TASK_PROJECT_MANAGER},\
	{400, USAGE_AL_LOG_JOURNAL_TIMECARD},\
	{401, USAGE_AL_CHECKBOOK_FINANCE},\
	{402, USAGE_AL_CALCULATOR},\
	{403, USAGE_AL_A_V_CAPTURE_PLAYBACK},\
	{404, USAGE_AL_LOCAL_MACHINE_BROWSER},\
	{405, USAGE_AL_LAN_WAN_BROWSER},\
	{406, USAGE_AL_INTERNET_BROWSER},\
	{407, USAGE_AL_REMOTE_NETWORKING_ISP_CONNECT},\
	{408, USAGE_AL_NETWORK_CONFERENCE},\
	{409, USAGE_AL_NETWORK_CHAT},\
	{410, USAGE_AL_TELEPHONY_DIALER},\
	{411, USAGE_AL_LOGON},\
	{412, USAGE_AL_LOGOFF},\
	{413, USAGE_AL_LOGON_LOGOFF},\
	{414, USAGE_AL_TERMINAL_LOCK_SCREENSAVER},\
	{415, USAGE_AL_CONTROL_PANEL},\
	{416, USAGE_AL_COMMAND_LINE_PROCESSOR_RUN},\
	{417, USAGE_AL_PROCESS_TASK_MANAGER},\
	{418, USAGE_AL_SELECT_TASK_APPLICATION},\
	{419, USAGE_AL_NEXT_TASK_APPLICATION},\
	{420, USAGE_AL_PREVIOUS_TASK_APPLICATION},\
	{421, USAGE_AL_PREEMPTIVE_HALT_TASK_APPLICATION},\
	{422, USAGE_AL_INTEGRATED_HELP_CENTER},\
	{423, USAGE_AL_DOCUMENTS},\
	{424, USAGE_AL_THESAURUS},\
	{425, USAGE_AL_DICTIONARY},\
	{426, USAGE_AL_DESKTOP},\
	{427, USAGE_AL_SPELL_CHECK},\
	{428, USAGE_AL_GRAMMAR_CHECK},\
	{429, USAGE_AL_WIRELESS_STATUS},\
	{430, USAGE_AL_KEYBOARD_LAYOUT},\
	{431, USAGE_AL_VIRUS_PROTECTION},\
	{432, USAGE_AL_ENCRYPTION},\
	{433, USAGE_AL_SCREEN_SAVER},\
	{434, USAGE_AL_ALARMS},\
	{435, USAGE_AL_CLOCK},\
	{436, USAGE_AL_FILE_BROWSER},\
	{437, USAGE_AL_POWER_STATUS},\
	{438, USAGE_AL_IMAGE_BROWSER},\
	{439, USAGE_AL_AUDIO_BROWSER},\
	{440, USAGE_AL_MOVIE_BROWSER},\
	{441, USAGE_AL_DIGITAL_RIGHTS_MANAGER},\
	{442, USAGE_AL_DIGITAL_WALLET},\
	{444, USAGE_AL_INSTANT_MESSAGING},\
	{445, USAGE_AL_OEM_FEATURES_TIPS_TUTORIAL_BROWSER},\
	{446, USAGE_AL_OEM_HELP},\
	{447, USAGE_AL_ONLINE_COMMUNITY},\
	{448, USAGE_AL_ENTERTAINMENT_CONTENT_BROWSER},\
	{449, USAGE_AL_ONLINE_SHOPPING_BROWSER},\
	{450, USAGE_AL_SMARTCARD_INFORMATION_HELP},\
	{451, USAGE_AL_MARKET_MONITOR_FINANCE_BROWSER},\
	{452, USAGE_AL_CUSTOMIZED_CORPORATE_NEWS_BROWSER},\
	{453, USAGE_AL_ONLINE_ACTIVITY_BROWSER},\
	{454, USAGE_AL_RESEARCH_SEARCH_BROWSER},\
	{455, USAGE_AL_AUDIO_PLAYER},\
	{456, USAGE_AL_MESSAGE_STATUS},\
	{457, USAGE_AL_CONTACT_SYNC},\
	{458, USAGE_AL_NAVIGATION},\
	{459, USAGE_AL_CONTEXT_AWARE_DESKTOP_ASSISTANT},\
	{512, USAGE_GENERIC_GUI_APPLICATION_CONTROLS},\
	{513, USAGE_AC_NEW},\
	{514, USAGE_AC_OPEN},\
	{515, USAGE_AC_CLOSE},\
	{516, USAGE_AC_EXIT},\
	{517, USAGE_AC_MAXIMIZE},\
	{518, USAGE_AC_MINIMIZE},\
	{519, USAGE_AC_SAVE},\
	{520, USAGE_AC_PRINT},\
	{521, USAGE_AC_PROPERTIES},\
	{538, USAGE_AC_UNDO},\
	{539, USAGE_AC_COPY},\
	{540, USAGE_AC_CUT},\
	{541, USAGE_AC_PASTE},\
	{542, USAGE_AC_SELECT_ALL},\
	{543, USAGE_AC_FIND},\
	{544, USAGE_AC_FIND_AND_REPLACE},\
	{545, USAGE_AC_SEARCH},\
	{546, USAGE_AC_GO_TO},\
	{547, USAGE_AC_HOME},\
	{548, USAGE_AC_BACK},\
	{549, USAGE_AC_FORWARD},\
	{550, USAGE_AC_STOP},\
	{551, USAGE_AC_REFRESH},\
	{552, USAGE_AC_PREVIOUS_LINK},\
	{553, USAGE_AC_NEXT_LINK},\
	{554, USAGE_AC_BOOKMARKS},\
	{555, USAGE_AC_HISTORY},\
	{556, USAGE_AC_SUBSCRIPTIONS},\
	{557, USAGE_AC_ZOOM_IN},\
	{558, USAGE_AC_ZOOM_OUT},\
	{559, USAGE_AC_ZOOM},\
	{560, USAGE_AC_FULL_SCREEN_VIEW},\
	{561, USAGE_AC_NORMAL_VIEW},\
	{562, USAGE_AC_VIEW_TOGGLE},\
	{563, USAGE_AC_SCROLL_UP},\
	{564, USAGE_AC_SCROLL_DOWN},\
	{565, USAGE_AC_SCROLL},\
	{566, USAGE_AC_PAN_LEFT},\
	{567, USAGE_AC_PAN_RIGHT},\
	{568, USAGE_AC_PAN},\
	{569, USAGE_AC_NEW_WINDOW},\
	{570, USAGE_AC_TILE_HORIZONTALLY},\
	{571, USAGE_AC_TILE_VERTICALLY},\
	{572, USAGE_AC_FORMAT},\
	{573, USAGE_AC_EDIT},\
	{574, USAGE_AC_BOLD},\
	{575, USAGE_AC_ITALICS},\
	{576, USAGE_AC_UNDERLINE},\
	{577, USAGE_AC_STRIKETHROUGH},\
	{578, USAGE_AC_SUBSCRIPT},\
	{579, USAGE_AC_SUPERSCRIPT},\
	{580, USAGE_AC_ALL_CAPS},\
	{581, USAGE_AC_ROTATE},\
	{582, USAGE_AC_RESIZE},\
	{583, USAGE_AC_FLIP_HORIZONTAL},\
	{584, USAGE_AC_FLIP_VERTICAL},\
	{585, USAGE_AC_MIRROR_HORIZONTAL},\
	{586, USAGE_AC_MIRROR_VERTICAL},\
	{587, USAGE_AC_FONT_SELECT},\
	{588, USAGE_AC_FONT_COLOR},\
	{589, USAGE_AC_FONT_SIZE},\
	{590, USAGE_AC_JUSTIFY_LEFT},\
	{591, USAGE_AC_JUSTIFY_CENTER_H},\
	{592, USAGE_AC_JUSTIFY_RIGHT},\
	{593, USAGE_AC_JUSTIFY_BLOCK_H},\
	{594, USAGE_AC_JUSTIFY_TOP},\
	{595, USAGE_AC_JUSTIFY_CENTER_V},\
	{596, USAGE_AC_JUSTIFY_BOTTOM},\
	{597, USAGE_AC_JUSTIFY_BLOCK_V},\
	{598, USAGE_AC_INDENT_DECREASE},\
	{599, USAGE_AC_INDENT_INCREASE},\
	{600, USAGE_AC_NUMBERED_LIST},\
	{601, USAGE_AC_RESTART_NUMBERING},\
	{602, USAGE_AC_BULLETED_LIST},\
	{603, USAGE_AC_PROMOTE},\
	{604, USAGE_AC_DEMOTE},\
	{605, USAGE_AC_YES},\
	{606, USAGE_AC_NO},\
	{607, USAGE_AC_CANCEL},\
	{608, USAGE_AC_CATALOG},\
	{609, USAGE_AC_BUY_CHECKOUT},\
	{610, USAGE_AC_ADD_TO_CART},\
	{611, USAGE_AC_EXPAND},\
	{612, USAGE_AC_EXPAND_ALL},\
	{613, USAGE_AC_COLLAPSE},\
	{614, USAGE_AC_COLLAPSE_ALL},\
	{615, USAGE_AC_PRINT_PREVIEW},\
	{616, USAGE_AC_PASTE_SPECIAL},\
	{617, USAGE_AC_INSERT_MODE},\
	{618, USAGE_AC_DELETE},\
	{619, USAGE_AC_LOCK},\
	{620, USAGE_AC_UNLOCK},\
	{621, USAGE_AC_PROTECT},\
	{622, USAGE_AC_UNPROTECT},\
	{623, USAGE_AC_ATTACH_COMMENT},\
	{624, USAGE_AC_DELETE_COMMENT},\
	{625, USAGE_AC_VIEW_COMMENT},\
	{626, USAGE_AC_SELECT_WORD},\
	{627, USAGE_AC_SELECT_SENTENCE},\
	{628, USAGE_AC_SELECT_PARAGRAPH},\
	{629, USAGE_AC_SELECT_COLUMN},\
	{630, USAGE_AC_SELECT_ROW},\
	{631, USAGE_AC_SELECT_TABLE},\
	{632, USAGE_AC_SELECT_OBJECT},\
	{633, USAGE_AC_REDO_REPEAT},\
	{634, USAGE_AC_SORT},\
	{635, USAGE_AC_SORT_ASCENDING},\
	{636, USAGE_AC_SORT_DESCENDING},\
	{637, USAGE_AC_FILTER},\
	{638, USAGE_AC_SET_CLOCK},\
	{639, USAGE_AC_VIEW_CLOCK},\
	{640, USAGE_AC_SELECT_TIME_ZONE},\
	{641, USAGE_AC_EDIT_TIME_ZONES},\
	{642, USAGE_AC_SET_ALARM},\
	{643, USAGE_AC_CLEAR_ALARM},\
	{644, USAGE_AC_SNOOZE_ALARM},\
	{645, USAGE_AC_RESET_ALARM},\
	{646, USAGE_AC_SYNCHRONIZE},\
	{647, USAGE_AC_SEND_RECEIVE},\
	{648, USAGE_AC_SEND_TO},\
	{649, USAGE_AC_REPLY},\
	{650, USAGE_AC_REPLY_ALL},\
	{651, USAGE_AC_FORWARD_MSG},\
	{652, USAGE_AC_SEND},\
	{653, USAGE_AC_ATTACH_FILE},\
	{654, USAGE_AC_UPLOAD},\
	{655, USAGE_AC_DOWNLOAD_SAVE_TARGET_AS_},\
	{656, USAGE_AC_SET_BORDERS},\
	{657, USAGE_AC_INSERT_ROW},\
	{658, USAGE_AC_INSERT_COLUMN},\
	{659, USAGE_AC_INSERT_FILE},\
	{660, USAGE_AC_INSERT_PICTURE},\
	{661, USAGE_AC_INSERT_OBJECT},\
	{662, USAGE_AC_INSERT_SYMBOL},\
	{663, USAGE_AC_SAVE_AND_CLOSE},\
	{664, USAGE_AC_RENAME},\
	{665, USAGE_AC_MERGE},\
	{666, USAGE_AC_SPLIT},\
	{667, USAGE_AC_DISRIBUTE_HORIZONTALLY},\
	{668, USAGE_AC_DISTRIBUTE_VERTICALLY},\
	{669, USAGE_AC_NEXT_KEYBOARD_LAYOUT_SELECT},\
	{670, USAGE_AC_NAVIGATION_GUIDANCE},\
	{671, USAGE_AC_DESKTOP_SHOW_ALL_WINDOWS},\
	{672, USAGE_AC_SOFT_KEY_LEFT},\
	{673, USAGE_AC_SOFT_KEY_RIGHT},\
	{674, USAGE_AC_DESKTOP_SHOW_ALL_APPLICATIONS},\
	{688, USAGE_AC_IDLE_KEEP_ALIVE},\
	{704, USAGE_EXTENDED_KEYBOARD_ATTRIBUTES_COLLECTION},\
	{705, USAGE_KEYBOARD_FORM_FACTOR},\
	{706, USAGE_KEYBOARD_KEY_TYPE},\
	{707, USAGE_KEYBOARD_PHYSICAL_LAYOUT},\
	{708, USAGE_VENDOR_SPECIFIC_KEYBOARD_PHYSICAL_LAYOUT},\
	{709, USAGE_KEYBOARD_IETF_LANGUAGE_TAG_INDEX},\
	{710, USAGE_IMPLEMENTED_KEYBOARD_INPUT_ASSIST_CONTROLS},\
	{711, USAGE_KEYBOARD_INPUT_ASSIST_PREVIOUS},\
	{712, USAGE_KEYBOARD_INPUT_ASSIST_NEXT},\
	{713, USAGE_KEYBOARD_INPUT_ASSIST_PREVIOUS_GROUP},\
	{714, USAGE_KEYBOARD_INPUT_ASSIST_NEXT_GROUP},\
	{715, USAGE_KEYBOARD_INPUT_ASSIST_ACCEPT},\
	{716, USAGE_KEYBOARD_INPUT_ASSIST_CANCEL},\
	{720, USAGE_PRIVACY_SCREEN_TOGGLE},\
	{721, USAGE_PRIVACY_SCREEN_LEVEL_DECREMENT},\
	{722, USAGE_PRIVACY_SCREEN_LEVEL_INCREMENT},\
	{723, USAGE_PRIVACY_SCREEN_LEVEL_MINIMUM},\
	{724, USAGE_PRIVACY_SCREEN_LEVEL_MAXIMUM},\
	{1280, USAGE_CONTACT_EDITED},\
	{1281, USAGE_CONTACT_ADDED},\
	{1282, USAGE_CONTACT_RECORD_ACTIVE},\
	{1283, USAGE_CONTACT_INDEX},\
	{1284, USAGE_CONTACT_NICKNAME},\
	{1285, USAGE_CONTACT_FIRST_NAME},\
	{1286, USAGE_CONTACT_LAST_NAME},\
	{1287, USAGE_CONTACT_FULL_NAME},\
	{1288, USAGE_CONTACT_PHONE_NUMBER_PERSONAL},\
	{1289, USAGE_CONTACT_PHONE_NUMBER_BUSINESS},\
	{1290, USAGE_CONTACT_PHONE_NUMBER_MOBILE},\
	{1291, USAGE_CONTACT_PHONE_NUMBER_PAGER},\
	{1292, USAGE_CONTACT_PHONE_NUMBER_FAX},\
	{1293, USAGE_CONTACT_PHONE_NUMBER_OTHER},\
	{1294, USAGE_CONTACT_EMAIL_PERSONAL},\
	{1295, USAGE_CONTACT_EMAIL_BUSINESS},\
	{1296, USAGE_CONTACT_EMAIL_OTHER},\
	{1297, USAGE_CONTACT_EMAIL_MAIN},\
	{1298, USAGE_CONTACT_SPEED_DIAL_NUMBER},\
	{1299, USAGE_CONTACT_STATUS_FLAG},\
	{1300, USAGE_CONTACT_MISC_},\
}}
