#define USAGE_POINTER "Pointer"
#define USAGE_MOUSE "Mouse"
#define USAGE_JOYSTICK "Joystick"
#define USAGE_GAMEPAD "Gamepad"
#define USAGE_KEYBOARD "Keyboard"
#define USAGE_KEYPAD "Keypad"
#define USAGE_MULTI_AXIS_CONTROLLER "Multi-axis Controller"
#define USAGE_TABLET_PC_SYSTEM_CONTROLS "Tablet PC System Controls"
#define USAGE_WATER_COOLING_DEVICE "Water Cooling Device"
#define USAGE_COMPUTER_CHASSIS_DEVICE "Computer Chassis Device"
#define USAGE_WIRELESS_RADIO_CONTROLS "Wireless Radio Controls"
#define USAGE_PORTABLE_DEVICE_CONTROL "Portable Device Control"
#define USAGE_SYSTEM_MULTI_AXIS_CONTROLLER "System Multi-Axis Controller"
#define USAGE_SPATIAL_CONTROLLER "Spatial Controller"
#define USAGE_ASSISTIVE_CONTROL "Assistive Control"
#define USAGE_DEVICE_DOCK "Device Dock"
#define USAGE_DOCKABLE_DEVICE "Dockable Device"
#define USAGE_CALL_STATE_MANAGEMENT_CONTROL "Call State Management Control"
#define USAGE_X "X"
#define USAGE_Y "Y"
#define USAGE_Z "Z"
#define USAGE_RX "Rx"
#define USAGE_RY "Ry"
#define USAGE_RZ "Rz"
#define USAGE_SLIDER "Slider"
#define USAGE_DIAL "Dial"
#define USAGE_WHEEL "Wheel"
#define USAGE_HAT_SWITCH "Hat Switch"
#define USAGE_COUNTED_BUFFER "Counted Buffer"
#define USAGE_BYTE_COUNT "Byte Count"
#define USAGE_MOTION_WAKEUP "Motion Wakeup"
#define USAGE_START "Start"
#define USAGE_SELECT "Select"
#define USAGE_VX "Vx"
#define USAGE_VY "Vy"
#define USAGE_VZ "Vz"
#define USAGE_VBRX "Vbrx"
#define USAGE_VBRY "Vbry"
#define USAGE_VBRZ "Vbrz"
#define USAGE_VNO "Vno"
#define USAGE_FEATURE_NOTIFICATION "Feature Notification"
#define USAGE_RESOLUTION_MULTIPLIER "Resolution Multiplier"
#define USAGE_QX "Qx"
#define USAGE_QY "Qy"
#define USAGE_QZ "Qz"
#define USAGE_QW "Qw"
#define USAGE_SYSTEM_CONTROL "System Control"
#define USAGE_SYSTEM_POWER_DOWN "System Power Down"
#define USAGE_SYSTEM_SLEEP "System Sleep"
#define USAGE_SYSTEM_WAKE_UP "System Wake Up"
#define USAGE_SYSTEM_CONTEXT_MENU "System Context Menu"
#define USAGE_SYSTEM_MAIN_MENU "System Main Menu"
#define USAGE_SYSTEM_APP_MENU "System App Menu"
#define USAGE_SYSTEM_MENU_HELP "System Menu Help"
#define USAGE_SYSTEM_MENU_EXIT "System Menu Exit"
#define USAGE_SYSTEM_MENU_SELECT "System Menu Select"
#define USAGE_SYSTEM_MENU_RIGHT "System Menu Right"
#define USAGE_SYSTEM_MENU_LEFT "System Menu Left"
#define USAGE_SYSTEM_MENU_UP "System Menu Up"
#define USAGE_SYSTEM_MENU_DOWN "System Menu Down"
#define USAGE_SYSTEM_COLD_RESTART "System Cold Restart"
#define USAGE_SYSTEM_WARM_RESTART "System Warm Restart"
#define USAGE_D_PAD_UP "D-pad Up"
#define USAGE_D_PAD_DOWN "D-pad Down"
#define USAGE_D_PAD_RIGHT "D-pad Right"
#define USAGE_D_PAD_LEFT "D-pad Left"
#define USAGE_INDEX_TRIGGER "Index Trigger"
#define USAGE_PALM_TRIGGER "Palm Trigger"
#define USAGE_THUMBSTICK "Thumbstick"
#define USAGE_SYSTEM_FUNCTION_SHIFT "System Function Shift"
#define USAGE_SYSTEM_FUNCTION_SHIFT_LOCK "System Function Shift Lock"
#define USAGE_SYSTEM_FUNCTION_SHIFT_LOCK_INDICATOR "System Function Shift Lock Indicator"
#define USAGE_SYSTEM_DISMISS_NOTIFICATION "System Dismiss Notification"
#define USAGE_SYSTEM_DO_NOT_DISTURB "System Do Not Disturb"
#define USAGE_SYSTEM_DOCK "System Dock"
#define USAGE_SYSTEM_UNDOCK "System Undock"
#define USAGE_SYSTEM_SETUP "System Setup"
#define USAGE_SYSTEM_BREAK "System Break"
#define USAGE_SYSTEM_DEBUGGER_BREAK "System Debugger Break"
#define USAGE_APPLICATION_BREAK "Application Break"
#define USAGE_APPLICATION_DEBUGGER_BREAK "Application Debugger Break"
#define USAGE_SYSTEM_SPEAKER_MUTE "System Speaker Mute"
#define USAGE_SYSTEM_HIBERNATE "System Hibernate"
#define USAGE_SYSTEM_DISPLAY_INVERT "System Display Invert"
#define USAGE_SYSTEM_DISPLAY_INTERNAL "System Display Internal"
#define USAGE_SYSTEM_DISPLAY_EXTERNAL "System Display External"
#define USAGE_SYSTEM_DISPLAY_BOTH "System Display Both"
#define USAGE_SYSTEM_DISPLAY_DUAL "System Display Dual"
#define USAGE_SYSTEM_DISPLAY_TOGGLE_INT_EXT_MODE "System Display Toggle Int/Ext Mode"
#define USAGE_SYSTEM_DISPLAY_SWAP_PRIMARY_SECONDARY "System Display Swap Primary/Secondary"
#define USAGE_SYSTEM_DISPLAY_TOGGLE_LCD_AUTOSCALE "System Display Toggle LCD Autoscale"
#define USAGE_SENSOR_ZONE "Sensor Zone"
#define USAGE_RPM "RPM"
#define USAGE_COOLANT_LEVEL "Coolant Level"
#define USAGE_COOLANT_CRITICAL_LEVEL "Coolant Critical Level"
#define USAGE_COOLANT_PUMP "Coolant Pump"
#define USAGE_CHASSIS_ENCLOSURE "Chassis Enclosure"
#define USAGE_WIRELESS_RADIO_BUTTON "Wireless Radio Button"
#define USAGE_WIRELESS_RADIO_LED "Wireless Radio LED"
#define USAGE_WIRELESS_RADIO_SLIDER_SWITCH "Wireless Radio Slider Switch"
#define USAGE_SYSTEM_DISPLAY_ROTATION_LOCK_BUTTON "System Display Rotation Lock Button"
#define USAGE_SYSTEM_DISPLAY_ROTATION_LOCK_SLIDER_SWITCH "System Display Rotation Lock Slider Switch"
#define USAGE_CONTROL_ENABLE "Control Enable"
#define USAGE_DOCKABLE_DEVICE_UNIQUE_ID "Dockable Device Unique ID"
#define USAGE_DOCKABLE_DEVICE_VENDOR_ID "Dockable Device Vendor ID"
#define USAGE_DOCKABLE_DEVICE_PRIMARY_USAGE_PAGE "Dockable Device Primary Usage Page"
#define USAGE_DOCKABLE_DEVICE_PRIMARY_USAGE_ID "Dockable Device Primary Usage ID"
#define USAGE_DOCKABLE_DEVICE_DOCKING_STATE "Dockable Device Docking State"
#define USAGE_DOCKABLE_DEVICE_DISPLAY_OCCLUSION "Dockable Device Display Occlusion"
#define USAGE_DOCKABLE_DEVICE_OBJECT_TYPE "Dockable Device Object Type"
#define USAGE_CALL_ACTIVE_LED "Call Active LED"
#define USAGE_CALL_MUTE_TOGGLE "Call Mute Toggle"
#define USAGE_CALL_MUTE_LED "Call Mute LED"


#define USAGE_PAGE_GENERIC_DESKTOP {"Generic Desktop", {\
	{1, USAGE_POINTER},\
	{2, USAGE_MOUSE},\
	{4, USAGE_JOYSTICK},\
	{5, USAGE_GAMEPAD},\
	{6, USAGE_KEYBOARD},\
	{7, USAGE_KEYPAD},\
	{8, USAGE_MULTI_AXIS_CONTROLLER},\
	{9, USAGE_TABLET_PC_SYSTEM_CONTROLS},\
	{10, USAGE_WATER_COOLING_DEVICE},\
	{11, USAGE_COMPUTER_CHASSIS_DEVICE},\
	{12, USAGE_WIRELESS_RADIO_CONTROLS},\
	{13, USAGE_PORTABLE_DEVICE_CONTROL},\
	{14, USAGE_SYSTEM_MULTI_AXIS_CONTROLLER},\
	{15, USAGE_SPATIAL_CONTROLLER},\
	{16, USAGE_ASSISTIVE_CONTROL},\
	{17, USAGE_DEVICE_DOCK},\
	{18, USAGE_DOCKABLE_DEVICE},\
	{19, USAGE_CALL_STATE_MANAGEMENT_CONTROL},\
	{48, USAGE_X},\
	{49, USAGE_Y},\
	{50, USAGE_Z},\
	{51, USAGE_RX},\
	{52, USAGE_RY},\
	{53, USAGE_RZ},\
	{54, USAGE_SLIDER},\
	{55, USAGE_DIAL},\
	{56, USAGE_WHEEL},\
	{57, USAGE_HAT_SWITCH},\
	{58, USAGE_COUNTED_BUFFER},\
	{59, USAGE_BYTE_COUNT},\
	{60, USAGE_MOTION_WAKEUP},\
	{61, USAGE_START},\
	{62, USAGE_SELECT},\
	{64, USAGE_VX},\
	{65, USAGE_VY},\
	{66, USAGE_VZ},\
	{67, USAGE_VBRX},\
	{68, USAGE_VBRY},\
	{69, USAGE_VBRZ},\
	{70, USAGE_VNO},\
	{71, USAGE_FEATURE_NOTIFICATION},\
	{72, USAGE_RESOLUTION_MULTIPLIER},\
	{73, USAGE_QX},\
	{74, USAGE_QY},\
	{75, USAGE_QZ},\
	{76, USAGE_QW},\
	{128, USAGE_SYSTEM_CONTROL},\
	{129, USAGE_SYSTEM_POWER_DOWN},\
	{130, USAGE_SYSTEM_SLEEP},\
	{131, USAGE_SYSTEM_WAKE_UP},\
	{132, USAGE_SYSTEM_CONTEXT_MENU},\
	{133, USAGE_SYSTEM_MAIN_MENU},\
	{134, USAGE_SYSTEM_APP_MENU},\
	{135, USAGE_SYSTEM_MENU_HELP},\
	{136, USAGE_SYSTEM_MENU_EXIT},\
	{137, USAGE_SYSTEM_MENU_SELECT},\
	{138, USAGE_SYSTEM_MENU_RIGHT},\
	{139, USAGE_SYSTEM_MENU_LEFT},\
	{140, USAGE_SYSTEM_MENU_UP},\
	{141, USAGE_SYSTEM_MENU_DOWN},\
	{142, USAGE_SYSTEM_COLD_RESTART},\
	{143, USAGE_SYSTEM_WARM_RESTART},\
	{144, USAGE_D_PAD_UP},\
	{145, USAGE_D_PAD_DOWN},\
	{146, USAGE_D_PAD_RIGHT},\
	{147, USAGE_D_PAD_LEFT},\
	{148, USAGE_INDEX_TRIGGER},\
	{149, USAGE_PALM_TRIGGER},\
	{150, USAGE_THUMBSTICK},\
	{151, USAGE_SYSTEM_FUNCTION_SHIFT},\
	{152, USAGE_SYSTEM_FUNCTION_SHIFT_LOCK},\
	{153, USAGE_SYSTEM_FUNCTION_SHIFT_LOCK_INDICATOR},\
	{154, USAGE_SYSTEM_DISMISS_NOTIFICATION},\
	{155, USAGE_SYSTEM_DO_NOT_DISTURB},\
	{160, USAGE_SYSTEM_DOCK},\
	{161, USAGE_SYSTEM_UNDOCK},\
	{162, USAGE_SYSTEM_SETUP},\
	{163, USAGE_SYSTEM_BREAK},\
	{164, USAGE_SYSTEM_DEBUGGER_BREAK},\
	{165, USAGE_APPLICATION_BREAK},\
	{166, USAGE_APPLICATION_DEBUGGER_BREAK},\
	{167, USAGE_SYSTEM_SPEAKER_MUTE},\
	{168, USAGE_SYSTEM_HIBERNATE},\
	{176, USAGE_SYSTEM_DISPLAY_INVERT},\
	{177, USAGE_SYSTEM_DISPLAY_INTERNAL},\
	{178, USAGE_SYSTEM_DISPLAY_EXTERNAL},\
	{179, USAGE_SYSTEM_DISPLAY_BOTH},\
	{180, USAGE_SYSTEM_DISPLAY_DUAL},\
	{181, USAGE_SYSTEM_DISPLAY_TOGGLE_INT_EXT_MODE},\
	{182, USAGE_SYSTEM_DISPLAY_SWAP_PRIMARY_SECONDARY},\
	{183, USAGE_SYSTEM_DISPLAY_TOGGLE_LCD_AUTOSCALE},\
	{192, USAGE_SENSOR_ZONE},\
	{193, USAGE_RPM},\
	{194, USAGE_COOLANT_LEVEL},\
	{195, USAGE_COOLANT_CRITICAL_LEVEL},\
	{196, USAGE_COOLANT_PUMP},\
	{197, USAGE_CHASSIS_ENCLOSURE},\
	{198, USAGE_WIRELESS_RADIO_BUTTON},\
	{199, USAGE_WIRELESS_RADIO_LED},\
	{200, USAGE_WIRELESS_RADIO_SLIDER_SWITCH},\
	{201, USAGE_SYSTEM_DISPLAY_ROTATION_LOCK_BUTTON},\
	{202, USAGE_SYSTEM_DISPLAY_ROTATION_LOCK_SLIDER_SWITCH},\
	{203, USAGE_CONTROL_ENABLE},\
	{208, USAGE_DOCKABLE_DEVICE_UNIQUE_ID},\
	{209, USAGE_DOCKABLE_DEVICE_VENDOR_ID},\
	{210, USAGE_DOCKABLE_DEVICE_PRIMARY_USAGE_PAGE},\
	{211, USAGE_DOCKABLE_DEVICE_PRIMARY_USAGE_ID},\
	{212, USAGE_DOCKABLE_DEVICE_DOCKING_STATE},\
	{213, USAGE_DOCKABLE_DEVICE_DISPLAY_OCCLUSION},\
	{214, USAGE_DOCKABLE_DEVICE_OBJECT_TYPE},\
	{224, USAGE_CALL_ACTIVE_LED},\
	{225, USAGE_CALL_MUTE_TOGGLE},\
	{226, USAGE_CALL_MUTE_LED},\
}}
