#pragma once

#define HID_ITEM_SIZE_MASK 0x03
#define HID_ITEM_TYPE_MASK 0x0C
#define HID_ITEM_TAG_MASK 0xF0

#define HID_ITEM_TYPE_MAIN 0x00
#define HID_ITEM_TYPE_GLOBAL 0x04
#define HID_ITEM_TYPE_LOCAL 0x08

#define HID_ITEM_SIZE_0 0x00
#define HID_ITEM_SIZE_8 0x01
#define HID_ITEM_SIZE_16 0x02
#define HID_ITEM_SIZE_32 0x03

#define HID_IOF_CONSTANT (1 << 0)
#define HID_IOF_DATA (0 << 0)
#define HID_IOF_VARIABLE (1 << 1)
#define HID_IOF_ARRAY (0 << 1)
#define HID_IOF_RELATIVE (1 << 2)
#define HID_IOF_ABSOLUTE (0 << 2)
#define HID_IOF_WRAP (1 << 3)
#define HID_IOF_NO_WRAP (0 << 3)
#define HID_IOF_NON_LINEAR (1 << 4)
#define HID_IOF_LINEAR (0 << 4)
#define HID_IOF_NO_PREFERRED_STATE (1 << 5)
#define HID_IOF_PREFERRED_STATE (0 << 5)
#define HID_IOF_NULLSTATE (1 << 6)
#define HID_IOF_NO_NULL_POSITION (0 << 6)
#define HID_IOF_VOLATILE (1 << 7)
#define HID_IOF_NON_VOLATILE (0 << 7)
#define HID_IOF_BUFFERED_BYTES (1 << 8)
#define HID_IOF_BITFIELD (0 << 8)

#define HID_ITEM_TYPE_TAG_INPUT (HID_ITEM_TYPE_MAIN | 0x80)
#define HID_ITEM_TYPE_TAG_OUTPUT (HID_ITEM_TYPE_MAIN | 0x90)
#define HID_ITEM_TYPE_TAG_COLLECTION (HID_ITEM_TYPE_MAIN | 0xA0)
#define HID_ITEM_TYPE_TAG_FEATURE (HID_ITEM_TYPE_MAIN | 0xB0)
#define HID_ITEM_TYPE_TAG_END_COLLECTION (HID_ITEM_TYPE_MAIN | 0xC0)
#define HID_ITEM_TYPE_TAG_USAGE_PAGE (HID_ITEM_TYPE_GLOBAL | 0x00)
#define HID_ITEM_TYPE_TAG_LOGICAL_MINIMUM (HID_ITEM_TYPE_GLOBAL | 0x10)
#define HID_ITEM_TYPE_TAG_LOGICAL_MAXIMUM (HID_ITEM_TYPE_GLOBAL | 0x20)
#define HID_ITEM_TYPE_TAG_PHYSICAL_MINIMUM (HID_ITEM_TYPE_GLOBAL | 0x30)
#define HID_ITEM_TYPE_TAG_PHYSICAL_MAXIMUM (HID_ITEM_TYPE_GLOBAL | 0x40)
#define HID_ITEM_TYPE_TAG_UNIT_EXPONENT (HID_ITEM_TYPE_GLOBAL | 0x50)
#define HID_ITEM_TYPE_TAG_UNIT (HID_ITEM_TYPE_GLOBAL | 0x60)
#define HID_ITEM_TYPE_TAG_REPORT_SIZE (HID_ITEM_TYPE_GLOBAL | 0x70)
#define HID_ITEM_TYPE_TAG_REPORT_ID (HID_ITEM_TYPE_GLOBAL | 0x80)
#define HID_ITEM_TYPE_TAG_REPORT_COUNT (HID_ITEM_TYPE_GLOBAL | 0x90)
#define HID_ITEM_TYPE_TAG_PUSH (HID_ITEM_TYPE_GLOBAL | 0xA0)
#define HID_ITEM_TYPE_TAG_POP (HID_ITEM_TYPE_GLOBAL | 0xB0)
#define HID_ITEM_TYPE_TAG_USAGE (HID_ITEM_TYPE_LOCAL | 0x00)
#define HID_ITEM_TYPE_TAG_USAGE_MINIMUM (HID_ITEM_TYPE_LOCAL | 0x10)
#define HID_ITEM_TYPE_TAG_USAGE_MAXIMUM (HID_ITEM_TYPE_LOCAL | 0x20)


