#define USAGE_ERRORROLLOVER "ErrorRollOver"
#define USAGE_POSTFAIL "POSTFail"
#define USAGE_ERRORUNDEFINED "ErrorUndefined"
#define USAGE_KEYBOARD_A "Keyboard A"
#define USAGE_KEYBOARD_B "Keyboard B"
#define USAGE_KEYBOARD_C "Keyboard C"
#define USAGE_KEYBOARD_D "Keyboard D"
#define USAGE_KEYBOARD_E "Keyboard E"
#define USAGE_KEYBOARD_F "Keyboard F"
#define USAGE_KEYBOARD_G "Keyboard G"
#define USAGE_KEYBOARD_H "Keyboard H"
#define USAGE_KEYBOARD_I "Keyboard I"
#define USAGE_KEYBOARD_J "Keyboard J"
#define USAGE_KEYBOARD_K "Keyboard K"
#define USAGE_KEYBOARD_L "Keyboard L"
#define USAGE_KEYBOARD_M "Keyboard M"
#define USAGE_KEYBOARD_N "Keyboard N"
#define USAGE_KEYBOARD_O "Keyboard O"
#define USAGE_KEYBOARD_P "Keyboard P"
#define USAGE_KEYBOARD_Q "Keyboard Q"
#define USAGE_KEYBOARD_R "Keyboard R"
#define USAGE_KEYBOARD_S "Keyboard S"
#define USAGE_KEYBOARD_T "Keyboard T"
#define USAGE_KEYBOARD_U "Keyboard U"
#define USAGE_KEYBOARD_V "Keyboard V"
#define USAGE_KEYBOARD_W "Keyboard W"
#define USAGE_KEYBOARD_X "Keyboard X"
#define USAGE_KEYBOARD_Y "Keyboard Y"
#define USAGE_KEYBOARD_Z "Keyboard Z"
#define USAGE_KEYBOARD_1_AND_BANG "Keyboard 1 and Bang"
#define USAGE_KEYBOARD_2_AND_AT "Keyboard 2 and At"
#define USAGE_KEYBOARD_3_AND_HASH "Keyboard 3 And Hash"
#define USAGE_KEYBOARD_4_AND_DOLLAR "Keyboard 4 and Dollar"
#define USAGE_KEYBOARD_5_AND_PERCENT "Keyboard 5 and Percent"
#define USAGE_KEYBOARD_6_AND_CARET "Keyboard 6 and Caret"
#define USAGE_KEYBOARD_7_AND_AMPERSAND "Keyboard 7 and Ampersand"
#define USAGE_KEYBOARD_8_AND_STAR "Keyboard 8 and Star"
#define USAGE_KEYBOARD_9_AND_LEFT_BRACKET "Keyboard 9 and Left Bracket"
#define USAGE_KEYBOARD_0_AND_RIGHT_BRACKET "Keyboard 0 and Right Bracket"
#define USAGE_KEYBOARD_RETURN_ENTER "Keyboard Return Enter"
#define USAGE_KEYBOARD_ESCAPE "Keyboard Escape"
#define USAGE_KEYBOARD_DELETE "Keyboard Delete"
#define USAGE_KEYBOARD_TAB "Keyboard Tab"
#define USAGE_KEYBOARD_SPACEBAR "Keyboard Spacebar"
#define USAGE_KEYBOARD_DASH_AND_UNDERSCORE "Keyboard Dash and Underscore"
#define USAGE_KEYBOARD_EQUALS_AND_PLUS "Keyboard Equals and Plus"
#define USAGE_KEYBOARD_LEFT_BRACE "Keyboard Left Brace"
#define USAGE_KEYBOARD_RIGHT_BRACE "Keyboard Right Brace"
#define USAGE_KEYBOARD_PIPE_AND_SLASH "Keyboard Pipe and Slash"
#define USAGE_KEYBOARD_NON_US "Keyboard Non-US"
#define USAGE_KEYBOARD_SEMICOLON_AND_COLON "Keyboard SemiColon and Colon"
#define USAGE_KEYBOARD_LEFT_APOS_AND_DOUBLE "Keyboard Left Apos and Double"
#define USAGE_KEYBOARD_GRAVE_ACCENT_AND_TILDE "Keyboard Grave Accent and Tilde"
#define USAGE_KEYBOARD_COMMA "Keyboard Comma"
#define USAGE_KEYBOARD_PERIOD "Keyboard Period"
#define USAGE_KEYBOARD_QUESTIONMARK "Keyboard QuestionMark"
#define USAGE_KEYBOARD_CAPS_LOCK "Keyboard Caps Lock"
#define USAGE_KEYBOARD_F1 "Keyboard F1"
#define USAGE_KEYBOARD_F2 "Keyboard F2"
#define USAGE_KEYBOARD_F3 "Keyboard F3"
#define USAGE_KEYBOARD_F4 "Keyboard F4"
#define USAGE_KEYBOARD_F5 "Keyboard F5"
#define USAGE_KEYBOARD_F6 "Keyboard F6"
#define USAGE_KEYBOARD_F7 "Keyboard F7"
#define USAGE_KEYBOARD_F8 "Keyboard F8"
#define USAGE_KEYBOARD_F9 "Keyboard F9"
#define USAGE_KEYBOARD_F10 "Keyboard F10"
#define USAGE_KEYBOARD_F11 "Keyboard F11"
#define USAGE_KEYBOARD_F12 "Keyboard F12"
#define USAGE_KEYBOARD_PRINTSCREEN "Keyboard PrintScreen"
#define USAGE_KEYBOARD_SCROLL_LOCK "Keyboard Scroll Lock"
#define USAGE_KEYBOARD_PAUSE "Keyboard Pause"
#define USAGE_KEYBOARD_INSERT "Keyboard Insert"
#define USAGE_KEYBOARD_HOME "Keyboard Home"
#define USAGE_KEYBOARD_PAGEUP "Keyboard PageUp"
#define USAGE_KEYBOARD_DELETE_FORWARD "Keyboard Delete Forward"
#define USAGE_KEYBOARD_END "Keyboard End"
#define USAGE_KEYBOARD_PAGEDOWN "Keyboard PageDown"
#define USAGE_KEYBOARD_RIGHTARROW "Keyboard RightArrow"
#define USAGE_KEYBOARD_LEFTARROW "Keyboard LeftArrow"
#define USAGE_KEYBOARD_DOWNARROW "Keyboard DownArrow"
#define USAGE_KEYBOARD_UPARROW "Keyboard UpArrow"
#define USAGE_KEYPAD_NUM_LOCK_AND_CLEAR "Keypad Num Lock and Clear"
#define USAGE_KEYPAD_FORWARD_SLASH "Keypad Forward Slash"
#define USAGE_KEYPAD_STAR "Keypad Star"
#define USAGE_KEYBOARD_DASH "Keyboard Dash"
#define USAGE_KEYPAD_PLUS "Keypad Plus"
#define USAGE_KEYPAD_ENTER "Keypad ENTER"
#define USAGE_KEYPAD_1_AND_END "Keypad 1 and End"
#define USAGE_KEYPAD_2_AND_DOWN_ARROW "Keypad 2 and Down Arrow"
#define USAGE_KEYPAD_3_AND_PAGEDN "Keypad 3 and PageDn"
#define USAGE_KEYPAD_4_AND_LEFT_ARROW "Keypad 4 and Left Arrow"
#define USAGE_KEYPAD_5 "Keypad 5"
#define USAGE_KEYPAD_6_AND_RIGHT_ARROW "Keypad 6 and Right Arrow"
#define USAGE_KEYPAD_7_AND_HOME "Keypad 7 and Home"
#define USAGE_KEYPAD_8_AND_UP_ARROW "Keypad 8 and Up Arrow"
#define USAGE_KEYPAD_9_AND_PAGEUP "Keypad 9 and PageUp"
#define USAGE_KEYPAD_0_AND_INSERT "Keypad 0 and Insert"
#define USAGE_KEYPAD_PERIOD "Keypad Period"
#define USAGE_KEYBOARD_NON_US_SLASH_BAR "Keyboard Non-US Slash Bar"
#define USAGE_KEYBOARD_APPLICATION "Keyboard Application"
#define USAGE_KEYBOARD_POWER "Keyboard Power"
#define USAGE_KEYPAD_EQUALS "Keypad Equals"
#define USAGE_KEYBOARD_F13 "Keyboard F13"
#define USAGE_KEYBOARD_F14 "Keyboard F14"
#define USAGE_KEYBOARD_F15 "Keyboard F15"
#define USAGE_KEYBOARD_F16 "Keyboard F16"
#define USAGE_KEYBOARD_F17 "Keyboard F17"
#define USAGE_KEYBOARD_F18 "Keyboard F18"
#define USAGE_KEYBOARD_F19 "Keyboard F19"
#define USAGE_KEYBOARD_F20 "Keyboard F20"
#define USAGE_KEYBOARD_F21 "Keyboard F21"
#define USAGE_KEYBOARD_F22 "Keyboard F22"
#define USAGE_KEYBOARD_F23 "Keyboard F23"
#define USAGE_KEYBOARD_F24 "Keyboard F24"
#define USAGE_KEYBOARD_EXECUTE "Keyboard Execute"
#define USAGE_KEYBOARD_HELP "Keyboard Help"
#define USAGE_KEYBOARD_MENU "Keyboard Menu"
#define USAGE_KEYBOARD_SELECT "Keyboard Select"
#define USAGE_KEYBOARD_STOP "Keyboard Stop"
#define USAGE_KEYBOARD_AGAIN "Keyboard Again"
#define USAGE_KEYBOARD_UNDO "Keyboard Undo"
#define USAGE_KEYBOARD_CUT "Keyboard Cut"
#define USAGE_KEYBOARD_COPY "Keyboard Copy"
#define USAGE_KEYBOARD_PASTE "Keyboard Paste"
#define USAGE_KEYBOARD_FIND "Keyboard Find"
#define USAGE_KEYBOARD_MUTE "Keyboard Mute"
#define USAGE_KEYBOARD_VOLUME_UP "Keyboard Volume Up"
#define USAGE_KEYBOARD_VOLUME_DOWN "Keyboard Volume Down"
#define USAGE_KEYBOARD_LOCKING_CAPS_LOCK "Keyboard Locking Caps Lock"
#define USAGE_KEYBOARD_LOCKING_NUM_LOCK "Keyboard Locking Num Lock"
#define USAGE_KEYBOARD_LOCKING_SCROLL_LOCK "Keyboard Locking Scroll Lock"
#define USAGE_KEYPAD_COMMA "Keypad Comma"
#define USAGE_KEYPAD_EQUAL_SIGN "Keypad Equal Sign"
#define USAGE_KEYBOARD_INTERNATIONAL1 "Keyboard International1"
#define USAGE_KEYBOARD_INTERNATIONAL2 "Keyboard International2"
#define USAGE_KEYBOARD_INTERNATIONAL3 "Keyboard International3"
#define USAGE_KEYBOARD_INTERNATIONAL4 "Keyboard International4"
#define USAGE_KEYBOARD_INTERNATIONAL5 "Keyboard International5"
#define USAGE_KEYBOARD_INTERNATIONAL6 "Keyboard International6"
#define USAGE_KEYBOARD_INTERNATIONAL7 "Keyboard International7"
#define USAGE_KEYBOARD_INTERNATIONAL8 "Keyboard International8"
#define USAGE_KEYBOARD_INTERNATIONAL9 "Keyboard International9"
#define USAGE_KEYBOARD_LANG1 "Keyboard LANG1"
#define USAGE_KEYBOARD_LANG2 "Keyboard LANG2"
#define USAGE_KEYBOARD_LANG3 "Keyboard LANG3"
#define USAGE_KEYBOARD_LANG4 "Keyboard LANG4"
#define USAGE_KEYBOARD_LANG5 "Keyboard LANG5"
#define USAGE_KEYBOARD_LANG6 "Keyboard LANG6"
#define USAGE_KEYBOARD_LANG7 "Keyboard LANG7"
#define USAGE_KEYBOARD_LANG8 "Keyboard LANG8"
#define USAGE_KEYBOARD_LANG9 "Keyboard LANG9"
#define USAGE_KEYBOARD_ALTERNATE_ERASE "Keyboard Alternate Erase"
#define USAGE_KEYBOARD_SYSREQ_ATTENTION "Keyboard SysReq Attention"
#define USAGE_KEYBOARD_CANCEL "Keyboard Cancel"
#define USAGE_KEYBOARD_CLEAR "Keyboard Clear"
#define USAGE_KEYBOARD_PRIOR "Keyboard Prior"
#define USAGE_KEYBOARD_RETURN "Keyboard Return"
#define USAGE_KEYBOARD_SEPARATOR "Keyboard Separator"
#define USAGE_KEYBOARD_OUT "Keyboard Out"
#define USAGE_KEYBOARD_OPER "Keyboard Oper"
#define USAGE_KEYBOARD_CLEAR_AGAIN "Keyboard Clear Again"
#define USAGE_KEYBOARD_CRSEL_PROPS "Keyboard CrSel Props"
#define USAGE_KEYBOARD_EXSEL "Keyboard ExSel"
#define USAGE_KEYPAD_DOUBLE_0 "Keypad Double 0"
#define USAGE_KEYPAD_TRIPLE_0 "Keypad Triple 0"
#define USAGE_THOUSANDS_SEPARATOR "Thousands Separator"
#define USAGE_DECIMAL_SEPARATOR "Decimal Separator"
#define USAGE_CURRENCY_UNIT "Currency Unit"
#define USAGE_CURRENCY_SUB_UNIT "Currency Sub-unit"
#define USAGE_KEYPAD_LEFT_BRACKET "Keypad Left Bracket"
#define USAGE_KEYPAD_RIGHT_BRACKET "Keypad Right Bracket"
#define USAGE_KEYPAD_LEFT_BRACE "Keypad Left Brace"
#define USAGE_KEYPAD_RIGHT_BRACE "Keypad Right Brace"
#define USAGE_KEYPAD_TAB "Keypad Tab"
#define USAGE_KEYPAD_BACKSPACE "Keypad Backspace"
#define USAGE_KEYPAD_A "Keypad A"
#define USAGE_KEYPAD_B "Keypad B"
#define USAGE_KEYPAD_C "Keypad C"
#define USAGE_KEYPAD_D "Keypad D"
#define USAGE_KEYPAD_E "Keypad E"
#define USAGE_KEYPAD_F "Keypad F"
#define USAGE_KEYPAD_XOR "Keypad XOR"
#define USAGE_KEYPAD_CARET "Keypad Caret"
#define USAGE_KEYPAD_PERCENTAGE "Keypad Percentage"
#define USAGE_KEYPAD_LESS "Keypad Less"
#define USAGE_KEYPAD_GREATER "Keypad Greater"
#define USAGE_KEYPAD_AMPERSAND "Keypad Ampersand"
#define USAGE_KEYPAD_DOUBLE_AMPERSAND "Keypad Double Ampersand"
#define USAGE_KEYPAD_BAR "Keypad Bar"
#define USAGE_KEYPAD_DOUBLE_BAR "Keypad Double Bar"
#define USAGE_KEYPAD_COLON "Keypad Colon"
#define USAGE_KEYPAD_HASH "Keypad Hash"
#define USAGE_KEYPAD_SPACE "Keypad Space"
#define USAGE_KEYPAD_AT "Keypad At"
#define USAGE_KEYPAD_BANG "Keypad Bang"
#define USAGE_KEYPAD_MEMORY_STORE "Keypad Memory Store"
#define USAGE_KEYPAD_MEMORY_RECALL "Keypad Memory Recall"
#define USAGE_KEYPAD_MEMORY_CLEAR "Keypad Memory Clear"
#define USAGE_KEYPAD_MEMORY_ADD "Keypad Memory Add"
#define USAGE_KEYPAD_MEMORY_SUBTRACT "Keypad Memory Subtract"
#define USAGE_KEYPAD_MEMORY_MULTIPLY "Keypad Memory Multiply"
#define USAGE_KEYPAD_MEMORY_DIVIDE "Keypad Memory Divide"
#define USAGE_KEYPAD_PLUS_MINUS "Keypad Plus Minus"
#define USAGE_KEYPAD_CLEAR "Keypad Clear"
#define USAGE_KEYPAD_CLEAR_ENTRY "Keypad Clear Entry"
#define USAGE_KEYPAD_BINARY "Keypad Binary"
#define USAGE_KEYPAD_OCTAL "Keypad Octal"
#define USAGE_KEYPAD_DECIMAL "Keypad Decimal"
#define USAGE_KEYPAD_HEXADECIMAL "Keypad Hexadecimal"
#define USAGE_KEYBOARD_LEFTCONTROL "Keyboard LeftControl"
#define USAGE_KEYBOARD_LEFTSHIFT "Keyboard LeftShift"
#define USAGE_KEYBOARD_LEFTALT "Keyboard LeftAlt"
#define USAGE_KEYBOARD_LEFT_GUI "Keyboard Left GUI"
#define USAGE_KEYBOARD_RIGHTCONTROL "Keyboard RightControl"
#define USAGE_KEYBOARD_RIGHTSHIFT "Keyboard RightShift"
#define USAGE_KEYBOARD_RIGHTALT "Keyboard RightAlt"
#define USAGE_KEYBOARD_RIGHT_GUI "Keyboard Right GUI"


#define USAGE_PAGE_KEYBOARD_KEYPAD {"Keyboard/Keypad", {\
	{1, USAGE_ERRORROLLOVER},\
	{2, USAGE_POSTFAIL},\
	{3, USAGE_ERRORUNDEFINED},\
	{4, USAGE_KEYBOARD_A},\
	{5, USAGE_KEYBOARD_B},\
	{6, USAGE_KEYBOARD_C},\
	{7, USAGE_KEYBOARD_D},\
	{8, USAGE_KEYBOARD_E},\
	{9, USAGE_KEYBOARD_F},\
	{10, USAGE_KEYBOARD_G},\
	{11, USAGE_KEYBOARD_H},\
	{12, USAGE_KEYBOARD_I},\
	{13, USAGE_KEYBOARD_J},\
	{14, USAGE_KEYBOARD_K},\
	{15, USAGE_KEYBOARD_L},\
	{16, USAGE_KEYBOARD_M},\
	{17, USAGE_KEYBOARD_N},\
	{18, USAGE_KEYBOARD_O},\
	{19, USAGE_KEYBOARD_P},\
	{20, USAGE_KEYBOARD_Q},\
	{21, USAGE_KEYBOARD_R},\
	{22, USAGE_KEYBOARD_S},\
	{23, USAGE_KEYBOARD_T},\
	{24, USAGE_KEYBOARD_U},\
	{25, USAGE_KEYBOARD_V},\
	{26, USAGE_KEYBOARD_W},\
	{27, USAGE_KEYBOARD_X},\
	{28, USAGE_KEYBOARD_Y},\
	{29, USAGE_KEYBOARD_Z},\
	{30, USAGE_KEYBOARD_1_AND_BANG},\
	{31, USAGE_KEYBOARD_2_AND_AT},\
	{32, USAGE_KEYBOARD_3_AND_HASH},\
	{33, USAGE_KEYBOARD_4_AND_DOLLAR},\
	{34, USAGE_KEYBOARD_5_AND_PERCENT},\
	{35, USAGE_KEYBOARD_6_AND_CARET},\
	{36, USAGE_KEYBOARD_7_AND_AMPERSAND},\
	{37, USAGE_KEYBOARD_8_AND_STAR},\
	{38, USAGE_KEYBOARD_9_AND_LEFT_BRACKET},\
	{39, USAGE_KEYBOARD_0_AND_RIGHT_BRACKET},\
	{40, USAGE_KEYBOARD_RETURN_ENTER},\
	{41, USAGE_KEYBOARD_ESCAPE},\
	{42, USAGE_KEYBOARD_DELETE},\
	{43, USAGE_KEYBOARD_TAB},\
	{44, USAGE_KEYBOARD_SPACEBAR},\
	{45, USAGE_KEYBOARD_DASH_AND_UNDERSCORE},\
	{46, USAGE_KEYBOARD_EQUALS_AND_PLUS},\
	{47, USAGE_KEYBOARD_LEFT_BRACE},\
	{48, USAGE_KEYBOARD_RIGHT_BRACE},\
	{49, USAGE_KEYBOARD_PIPE_AND_SLASH},\
	{50, USAGE_KEYBOARD_NON_US},\
	{51, USAGE_KEYBOARD_SEMICOLON_AND_COLON},\
	{52, USAGE_KEYBOARD_LEFT_APOS_AND_DOUBLE},\
	{53, USAGE_KEYBOARD_GRAVE_ACCENT_AND_TILDE},\
	{54, USAGE_KEYBOARD_COMMA},\
	{55, USAGE_KEYBOARD_PERIOD},\
	{56, USAGE_KEYBOARD_QUESTIONMARK},\
	{57, USAGE_KEYBOARD_CAPS_LOCK},\
	{58, USAGE_KEYBOARD_F1},\
	{59, USAGE_KEYBOARD_F2},\
	{60, USAGE_KEYBOARD_F3},\
	{61, USAGE_KEYBOARD_F4},\
	{62, USAGE_KEYBOARD_F5},\
	{63, USAGE_KEYBOARD_F6},\
	{64, USAGE_KEYBOARD_F7},\
	{65, USAGE_KEYBOARD_F8},\
	{66, USAGE_KEYBOARD_F9},\
	{67, USAGE_KEYBOARD_F10},\
	{68, USAGE_KEYBOARD_F11},\
	{69, USAGE_KEYBOARD_F12},\
	{70, USAGE_KEYBOARD_PRINTSCREEN},\
	{71, USAGE_KEYBOARD_SCROLL_LOCK},\
	{72, USAGE_KEYBOARD_PAUSE},\
	{73, USAGE_KEYBOARD_INSERT},\
	{74, USAGE_KEYBOARD_HOME},\
	{75, USAGE_KEYBOARD_PAGEUP},\
	{76, USAGE_KEYBOARD_DELETE_FORWARD},\
	{77, USAGE_KEYBOARD_END},\
	{78, USAGE_KEYBOARD_PAGEDOWN},\
	{79, USAGE_KEYBOARD_RIGHTARROW},\
	{80, USAGE_KEYBOARD_LEFTARROW},\
	{81, USAGE_KEYBOARD_DOWNARROW},\
	{82, USAGE_KEYBOARD_UPARROW},\
	{83, USAGE_KEYPAD_NUM_LOCK_AND_CLEAR},\
	{84, USAGE_KEYPAD_FORWARD_SLASH},\
	{85, USAGE_KEYPAD_STAR},\
	{86, USAGE_KEYBOARD_DASH},\
	{87, USAGE_KEYPAD_PLUS},\
	{88, USAGE_KEYPAD_ENTER},\
	{89, USAGE_KEYPAD_1_AND_END},\
	{90, USAGE_KEYPAD_2_AND_DOWN_ARROW},\
	{91, USAGE_KEYPAD_3_AND_PAGEDN},\
	{92, USAGE_KEYPAD_4_AND_LEFT_ARROW},\
	{93, USAGE_KEYPAD_5},\
	{94, USAGE_KEYPAD_6_AND_RIGHT_ARROW},\
	{95, USAGE_KEYPAD_7_AND_HOME},\
	{96, USAGE_KEYPAD_8_AND_UP_ARROW},\
	{97, USAGE_KEYPAD_9_AND_PAGEUP},\
	{98, USAGE_KEYPAD_0_AND_INSERT},\
	{99, USAGE_KEYPAD_PERIOD},\
	{100, USAGE_KEYBOARD_NON_US_SLASH_BAR},\
	{101, USAGE_KEYBOARD_APPLICATION},\
	{102, USAGE_KEYBOARD_POWER},\
	{103, USAGE_KEYPAD_EQUALS},\
	{104, USAGE_KEYBOARD_F13},\
	{105, USAGE_KEYBOARD_F14},\
	{106, USAGE_KEYBOARD_F15},\
	{107, USAGE_KEYBOARD_F16},\
	{108, USAGE_KEYBOARD_F17},\
	{109, USAGE_KEYBOARD_F18},\
	{110, USAGE_KEYBOARD_F19},\
	{111, USAGE_KEYBOARD_F20},\
	{112, USAGE_KEYBOARD_F21},\
	{113, USAGE_KEYBOARD_F22},\
	{114, USAGE_KEYBOARD_F23},\
	{115, USAGE_KEYBOARD_F24},\
	{116, USAGE_KEYBOARD_EXECUTE},\
	{117, USAGE_KEYBOARD_HELP},\
	{118, USAGE_KEYBOARD_MENU},\
	{119, USAGE_KEYBOARD_SELECT},\
	{120, USAGE_KEYBOARD_STOP},\
	{121, USAGE_KEYBOARD_AGAIN},\
	{122, USAGE_KEYBOARD_UNDO},\
	{123, USAGE_KEYBOARD_CUT},\
	{124, USAGE_KEYBOARD_COPY},\
	{125, USAGE_KEYBOARD_PASTE},\
	{126, USAGE_KEYBOARD_FIND},\
	{127, USAGE_KEYBOARD_MUTE},\
	{128, USAGE_KEYBOARD_VOLUME_UP},\
	{129, USAGE_KEYBOARD_VOLUME_DOWN},\
	{130, USAGE_KEYBOARD_LOCKING_CAPS_LOCK},\
	{131, USAGE_KEYBOARD_LOCKING_NUM_LOCK},\
	{132, USAGE_KEYBOARD_LOCKING_SCROLL_LOCK},\
	{133, USAGE_KEYPAD_COMMA},\
	{134, USAGE_KEYPAD_EQUAL_SIGN},\
	{135, USAGE_KEYBOARD_INTERNATIONAL1},\
	{136, USAGE_KEYBOARD_INTERNATIONAL2},\
	{137, USAGE_KEYBOARD_INTERNATIONAL3},\
	{138, USAGE_KEYBOARD_INTERNATIONAL4},\
	{139, USAGE_KEYBOARD_INTERNATIONAL5},\
	{140, USAGE_KEYBOARD_INTERNATIONAL6},\
	{141, USAGE_KEYBOARD_INTERNATIONAL7},\
	{142, USAGE_KEYBOARD_INTERNATIONAL8},\
	{143, USAGE_KEYBOARD_INTERNATIONAL9},\
	{144, USAGE_KEYBOARD_LANG1},\
	{145, USAGE_KEYBOARD_LANG2},\
	{146, USAGE_KEYBOARD_LANG3},\
	{147, USAGE_KEYBOARD_LANG4},\
	{148, USAGE_KEYBOARD_LANG5},\
	{149, USAGE_KEYBOARD_LANG6},\
	{150, USAGE_KEYBOARD_LANG7},\
	{151, USAGE_KEYBOARD_LANG8},\
	{152, USAGE_KEYBOARD_LANG9},\
	{153, USAGE_KEYBOARD_ALTERNATE_ERASE},\
	{154, USAGE_KEYBOARD_SYSREQ_ATTENTION},\
	{155, USAGE_KEYBOARD_CANCEL},\
	{156, USAGE_KEYBOARD_CLEAR},\
	{157, USAGE_KEYBOARD_PRIOR},\
	{158, USAGE_KEYBOARD_RETURN},\
	{159, USAGE_KEYBOARD_SEPARATOR},\
	{160, USAGE_KEYBOARD_OUT},\
	{161, USAGE_KEYBOARD_OPER},\
	{162, USAGE_KEYBOARD_CLEAR_AGAIN},\
	{163, USAGE_KEYBOARD_CRSEL_PROPS},\
	{164, USAGE_KEYBOARD_EXSEL},\
	{176, USAGE_KEYPAD_DOUBLE_0},\
	{177, USAGE_KEYPAD_TRIPLE_0},\
	{178, USAGE_THOUSANDS_SEPARATOR},\
	{179, USAGE_DECIMAL_SEPARATOR},\
	{180, USAGE_CURRENCY_UNIT},\
	{181, USAGE_CURRENCY_SUB_UNIT},\
	{182, USAGE_KEYPAD_LEFT_BRACKET},\
	{183, USAGE_KEYPAD_RIGHT_BRACKET},\
	{184, USAGE_KEYPAD_LEFT_BRACE},\
	{185, USAGE_KEYPAD_RIGHT_BRACE},\
	{186, USAGE_KEYPAD_TAB},\
	{187, USAGE_KEYPAD_BACKSPACE},\
	{188, USAGE_KEYPAD_A},\
	{189, USAGE_KEYPAD_B},\
	{190, USAGE_KEYPAD_C},\
	{191, USAGE_KEYPAD_D},\
	{192, USAGE_KEYPAD_E},\
	{193, USAGE_KEYPAD_F},\
	{194, USAGE_KEYPAD_XOR},\
	{195, USAGE_KEYPAD_CARET},\
	{196, USAGE_KEYPAD_PERCENTAGE},\
	{197, USAGE_KEYPAD_LESS},\
	{198, USAGE_KEYPAD_GREATER},\
	{199, USAGE_KEYPAD_AMPERSAND},\
	{200, USAGE_KEYPAD_DOUBLE_AMPERSAND},\
	{201, USAGE_KEYPAD_BAR},\
	{202, USAGE_KEYPAD_DOUBLE_BAR},\
	{203, USAGE_KEYPAD_COLON},\
	{204, USAGE_KEYPAD_HASH},\
	{205, USAGE_KEYPAD_SPACE},\
	{206, USAGE_KEYPAD_AT},\
	{207, USAGE_KEYPAD_BANG},\
	{208, USAGE_KEYPAD_MEMORY_STORE},\
	{209, USAGE_KEYPAD_MEMORY_RECALL},\
	{210, USAGE_KEYPAD_MEMORY_CLEAR},\
	{211, USAGE_KEYPAD_MEMORY_ADD},\
	{212, USAGE_KEYPAD_MEMORY_SUBTRACT},\
	{213, USAGE_KEYPAD_MEMORY_MULTIPLY},\
	{214, USAGE_KEYPAD_MEMORY_DIVIDE},\
	{215, USAGE_KEYPAD_PLUS_MINUS},\
	{216, USAGE_KEYPAD_CLEAR},\
	{217, USAGE_KEYPAD_CLEAR_ENTRY},\
	{218, USAGE_KEYPAD_BINARY},\
	{219, USAGE_KEYPAD_OCTAL},\
	{220, USAGE_KEYPAD_DECIMAL},\
	{221, USAGE_KEYPAD_HEXADECIMAL},\
	{224, USAGE_KEYBOARD_LEFTCONTROL},\
	{225, USAGE_KEYBOARD_LEFTSHIFT},\
	{226, USAGE_KEYBOARD_LEFTALT},\
	{227, USAGE_KEYBOARD_LEFT_GUI},\
	{228, USAGE_KEYBOARD_RIGHTCONTROL},\
	{229, USAGE_KEYBOARD_RIGHTSHIFT},\
	{230, USAGE_KEYBOARD_RIGHTALT},\
	{231, USAGE_KEYBOARD_RIGHT_GUI},\
}}
